export const CONTINUITY = '[VXG RealForever]';
export const VERSION = 'v0.2.0-RC1';
export const TASK_SCHEMA_VERSION = 'vex.relay.task/v2';
export const RESULT_SCHEMA_VERSION = 'vex.relay.result/v2';
export const FORWARD_STATE_SCHEMA_VERSION = 'vex.relay.forward-state/v2';
export const LEGACY_FORWARD_STATE_SCHEMA_VERSION = 'vex.relay.forward-state/v1';
export const INPUT_PACKAGE_SCHEMA_VERSION = 'vex.relay.input-package/v2';
export const RETURN_INVENTORY_SCHEMA_VERSION = 'vex.relay.return-inventory/v2';

export const PUBLIC_PRIMITIVES = Object.freeze([
  'AUTH', 'READ', 'QUERY', 'WRITE', 'RUN',
  'CHECK', 'PUBLISH', 'LISTEN', 'RESPOND', 'LOOP',
]);

export const PRIMITIVE_SET = new Set(PUBLIC_PRIMITIVES);
export const MUTATING_PRIMITIVES = new Set(['WRITE', 'PUBLISH']);
export const LOOP_ALLOWED_PRIMITIVES = new Set(['AUTH', 'READ', 'QUERY', 'CHECK', 'LISTEN']);

export const ROLE_STATES = new Set([
  'OPERATIONS', 'CODER', 'INDEPENDENT_ASSURANCE',
  'LIFECYCLE_OPERATIONS', 'PROJECT_PROTOCOL_MAINTENANCE',
]);

export const ENTRY_CLASSES = new Set([
  'NEW_ROOT_ALLOCATION', 'SAME_LANE_SUCCESSOR', 'SAME_LANE_ROLE_TRANSITION',
  'RETURN_CONSUMPTION', 'FOUNDATION_DELTA', 'TERMINAL_REENTRY',
]);

export const SCOPE_MODES = new Set(['FULL_LOCAL_LIFECYCLE', 'STAGE_BOUNDED', 'READ_ONLY']);
export const COMPLETION_PROGRESS_MODES = new Set(['MAXIMAL_SAFE_PROGRESS', 'EXACT_STAGE_GATE']);
export const COMPLETION_TARGETS = new Set([
  'TERMINAL_LOCAL_RETURN', 'SOURCE_PUBLICATION', 'HOSTED_EVIDENCE',
  'ASSURANCE_DISPOSITION', 'EXACT_NAMED_GATE',
]);
export const HUMAN_ROUND_TRIP_POLICIES = new Set(['IRREDUCIBLE_ONLY']);
export const CONTINUATION_DIRECTIVES = new Set([
  'AUTO_CONTINUE', 'AUTO_ROLE_TRANSITION', 'HOST_HANDOFF_REQUIRED',
  'USER_ACTION_REQUIRED', 'STOP_FOR_CLASSIFICATION', 'STAGE_RETURN', 'TERMINAL',
]);
export const STOP_REASON_CLASSES = new Set([
  'TERMINAL', 'CAGE', 'USER_ACTION_REQUIRED', 'AUTHORITY_UNAVAILABLE',
  'EVIDENCE_REJECTED', 'EXECUTION_SURFACE_REQUIRED', 'PROTECTED_DECISION_REQUIRED',
  'STAGE_GATE_REACHED',
]);
export const MAXIMAL_SAFE_STOP_REASONS = Object.freeze([
  'TERMINAL', 'CAGE', 'USER_ACTION_REQUIRED', 'AUTHORITY_UNAVAILABLE',
  'EVIDENCE_REJECTED', 'EXECUTION_SURFACE_REQUIRED', 'PROTECTED_DECISION_REQUIRED',
]);
export const CAPABILITY_STATES = new Set(['AVAILABLE', 'UNAVAILABLE', 'UNKNOWN']);
export const CONFLICT_STATES = new Set(['NONE', 'CONFLICT', 'UNKNOWN']);
export const REMOTE_OBSERVATION_OWNERS = new Set(['Operations', 'LocalRelay']);
export const WORKSPACE_MODES = new Set(['VEX_HOME', 'RUN_ROOT', 'EXISTING_ENV_PATH']);
export const REPOSITORY_MODES = new Set(['EXISTING_PATH', 'CLONE_IN_WORKSPACE']);
export const REPOSITORY_CLONE_TRANSPORTS = new Set(['GIT', 'GITHUB_GH']);
export const CANDIDATE_STATES = new Set(['FORMING', 'EXACT']);

export const LIFECYCLE_STATES = new Set([
  'ALLOCATED', 'GROUNDED', 'SOURCE_MUTATION_PENDING', 'CODER_ACTIVE',
  'SOURCE_READY', 'PUBLICATION_PENDING', 'CANDIDATE_PUBLISHED',
  'HOSTED_EVIDENCE_PENDING', 'ASSURANCE_PENDING', 'ASSURANCE_EVIDENCE_READY',
  'CORRECTION_REQUIRED', 'CLEAR_ON_EXACT_HEAD', 'LIFECYCLE_EFFECT_PENDING',
  'POST_MERGE_EVIDENCE_PENDING', 'TERMINAL_RETURN_PENDING',
  'TERMINAL_RETURNED', 'AUTHENTICATION_REQUIRED', 'BLOCKED', 'CAGE',
]);

export const DISPOSITIONS = new Set([
  'PASS', 'HOSTED_VALIDATION_PENDING', 'USER_ACTION_REQUIRED',
  'SAFE_FAILURE', 'PARTIAL_FAIL_CLOSED',
]);

export const EFFECT_BY_PRIMITIVE = Object.freeze({
  AUTH: 'CHECK_AUTH',
  READ: 'READ_REPOSITORY',
  QUERY: 'QUERY_PROVIDER',
  WRITE: 'WRITE_SOURCE',
  RUN: 'RUN_LOCAL_COMMAND',
  CHECK: 'CHECK_STATE',
  LISTEN: 'WAIT_REMOTE',
  RESPOND: 'FORM_RESULT',
  LOOP: 'LOOP_BOUNDED',
});

export const PUBLISH_EFFECT_BY_ACTION = Object.freeze({
  PREPARE_BRANCH: 'CREATE_BRANCH',
  COMMIT: 'CREATE_COMMIT',
  PUSH: 'PUSH_BRANCH',
  PULL_REQUEST: 'CREATE_PULL_REQUEST',
  UPDATE_PULL_REQUEST_BODY: 'UPDATE_COORDINATION_METADATA',
});

export const REPOSITORY_ACTIONS = Object.freeze({
  AUTH: new Set(['GITHUB_GH', 'GIT_REMOTE_READ', 'GIT_PUSH_DRY_RUN']),
  READ: new Set(['REPOSITORY_STATE', 'FILE', 'LIST', 'DIFF', 'PACKAGE_FILE']),
  QUERY: new Set([
    'PULL_REQUEST', 'ISSUE', 'RUN', 'RUN_LOG', 'CHANGED_PATHS',
    'REVIEW_SNAPSHOT', 'REMOTE_REVIEW_SNAPSHOT', 'PR_CHECKS',
  ]),
  WRITE: new Set(['COPY_FILE', 'REPLACE_TEXT', 'DELETE_FILE']),
  RUN: new Set(['COMMAND']),
  CHECK: new Set([
    'COMMAND', 'CLEAN_WORKTREE', 'EXPECTED_HEAD', 'EXPECTED_TREE',
    'REMOTE_BASE_HEAD', 'REMOTE_BRANCH_ABSENT', 'REMOTE_BRANCH_HEAD',
    'OPEN_PR_PATH_OVERLAP_CLEAR', 'PATHS_WITHIN_MEMBRANE',
    'DIFF_NONEMPTY', 'EXPECTED_CHANGED_PATHS_EXACT', 'FILE_HASH',
  ]),
  PUBLISH: new Set(['PREPARE_BRANCH', 'COMMIT', 'PUSH', 'PULL_REQUEST', 'UPDATE_PULL_REQUEST_BODY']),
  LISTEN: new Set(['RUN', 'PR_CHECKS']),
  RESPOND: new Set(['CANONICAL_RETURN']),
  LOOP: new Set(['UNTIL']),
});

export const RETURN_FILES = Object.freeze([
  'RESULT-SUMMARY.txt',
  'result.json',
  'execution.log',
  'before-state.json',
  'after-state.json',
  'inventory.json',
  'evidence.json',
  'forward-state.json',
  'candidate.diff',
  'selected-source-files.json',
]);

export const DEFAULT_SAFE_ENV_KEYS = Object.freeze([
  'PATH', 'PATHEXT', 'SystemRoot', 'WINDIR', 'HOME', 'USERPROFILE',
  'LOCALAPPDATA', 'APPDATA', 'TMP', 'TEMP', 'TMPDIR', 'ComSpec',
  'SSH_AUTH_SOCK', 'XDG_CONFIG_HOME', 'LANG', 'LC_ALL',
]);

export const SECRET_ENV_PATTERN = /(TOKEN|PASSWORD|PASSWD|SECRET|PRIVATE_KEY|API_KEY|AUTHORIZATION|COOKIE|SESSION)/i;
