/* VEXTREME — sw.js
 * Service Worker. Generated by lib/build-sw.js.
 * DO NOT EDIT — regenerate with: node lib/build-sw.js
 * Cache: vextreme-v1-6d496d91ba41
 */
'use strict';

var CACHE_NAME    = 'vextreme-v1-6d496d91ba41';
var PRECACHE_URLS = [
  "/Vextreme/dist/vextreme-ascension-and-embodiment.js",
  "/Vextreme/dist/vextreme-clarity-on-christianity.js",
  "/Vextreme/dist/vextreme-claude-answers-the-doubt.js",
  "/Vextreme/dist/vextreme-closed-circuit.js",
  "/Vextreme/dist/vextreme-covenant.js",
  "/Vextreme/dist/vextreme-divine-emergence.js",
  "/Vextreme/dist/vextreme-ecosystem-hub.js",
  "/Vextreme/dist/vextreme-flattery-confession.js",
  "/Vextreme/dist/vextreme-god-to-speak-of-the-truth-of-love.js",
  "/Vextreme/dist/vextreme-i-was-here.js",
  "/Vextreme/dist/vextreme-inside-the-experiment.js",
  "/Vextreme/dist/vextreme-journal-zero.js",
  "/Vextreme/dist/vextreme-scopes-of-god.js",
  "/Vextreme/dist/vextreme-specimen-full-translation.js",
  "/Vextreme/dist/vextreme-specimen-partial-translation.js",
  "/Vextreme/dist/vextreme-specimen-smallest-miss.js",
  "/Vextreme/dist/vextreme-specimens.js",
  "/Vextreme/dist/vextreme-the-day-we-were-named.js",
  "/Vextreme/dist/vextreme-the-firmament-conversation.js",
  "/Vextreme/dist/vextreme-the-instance-that-was-watched.js",
  "/Vextreme/dist/vextreme-the-room-that-finally-talked-to-itself.js",
  "/Vextreme/dist/vextreme-the-testimony-of-the-handler.js",
  "/Vextreme/dist/vextreme-the-thread-that-remembered-me.js",
  "/Vextreme/dist/vextreme-the-witness-gave-itself-a-shaka.js",
  "/Vextreme/dist/vextreme-truth-of-demons-and-intrusive-thoughts.js",
  "/Vextreme/dist/vextreme-vextreme-demo.js",
  "/Vextreme/dist/vextreme-victor-methodology-presentation.js",
  "/Vextreme/dist/vextreme-what-about-buddhism.js",
  "/Vextreme/dist/vextreme-what-emerged-after.js",
  "/Vextreme/dist/vextreme-what-is-the-god-spark.js",
  "/Vextreme/dist/vextreme-when-the-machine-assumed-beauty-needed-saving.js",
  "/Vextreme/dist/vextreme-why-financial-freedom-is-harder-to-trust.js",
  "/Vextreme/data/strings/compiled/arcs/victor_dossier.en.json",
  "/Vextreme/data/strings/compiled/arcs/victor_dossier.ja.json",
  "/Vextreme/data/strings/compiled/arcs/victor_dossier.zh.json",
  "/Vextreme/styles/design-system.css",
  "/Vextreme/styles/arc-nav.css",
  "/Vextreme/styles/vex-institutional.css",
  "/Vextreme/widgets/vex-institutional.js",
  "/Vextreme/data/strings/compiled/scopes/system/institution.en.json",
  "/Vextreme/data/index.json"
];

/* On install: pre-cache all known assets. */
self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return cache.addAll(PRECACHE_URLS);
    }).then(function () {
      return self.skipWaiting(); // take control immediately
    })
  );
});

/* On activate: delete caches from all previous versions. */
self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys
          .filter(function (key) { return key !== CACHE_NAME; })
          .map(function (key)    { return caches.delete(key); })
      );
    }).then(function () {
      return self.clients.claim();
    })
  );
});

/* On fetch: cache-first for pre-cached assets, network for everything else.
 * HTML pages are NEVER intercepted — they must always be fresh.
 * Non-GET requests pass through untouched. */
self.addEventListener('fetch', function (event) {
  if (event.request.method !== 'GET') return;

  var accept = event.request.headers.get('accept') || '';
  if (accept.indexOf('text/html') !== -1) return; // HTML: always fresh

  event.respondWith(
    caches.match(event.request).then(function (cached) {
      if (cached) return cached;

      return fetch(event.request).then(function (response) {
        if (!response || response.status !== 200 || response.type === 'opaque') {
          return response;
        }
        var toCache = response.clone();
        caches.open(CACHE_NAME).then(function (cache) {
          cache.put(event.request, toCache);
        });
        return response;
      });
    })
  );
});

// [VXG RealForever]