/**
 * VEXTREME — widgets/fab-theme.js
 *
 * Dark/light theme toggle orb. Persists the choice to localStorage and sets
 * document.documentElement's data-theme attribute — the same attribute
 * convention styles/design-system.css already uses for its
 * [data-theme="dashboard"] block, generalized to a plain "dark"/"light"
 * value any page's own CSS can key off.
 *
 * Honest scope note: this ships the real toggle MECHANISM (persisted state,
 * the attribute, an icon that reflects current state) — it does not itself
 * add [data-theme="dark"] CSS overrides to the ~100+ content pages that each
 * hand-author their own inline :root token block rather than sharing
 * styles/design-system.css. A page with no dark-theme CSS of its own simply
 * shows no visible change when toggled; the toggle is still real and
 * correctly persisted, so a page that DOES add dark CSS later needs zero
 * JS changes to pick it up. Retrofitting per-page dark CSS is a separate,
 * much larger task — not attempted here.
 *
 * Mounts an orb into #vex-spiral-group if present (Session 025's FAB
 * unification — see widgets/vex-fab.js), else falls back to its own
 * top-level fixed-position button for standalone/pre-spiral-fab use.
 *
 * Self-contained IIFE — no global exports, no framework dependencies.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : dark/light theme toggle orb — sets document.documentElement's data-theme attribute, persists to localStorage
 *   reads     : localStorage (vex-theme — persisted preference)
 *               document.documentElement's data-theme attribute (current state)
 *   writes    : document.documentElement's data-theme attribute
 *               localStorage (vex-theme)
 *   loaded-by : lib/build-vextreme.js (inlined as theme feature in God Scripts)
 *               tests/08-build-vextreme.test.js
 *   tested-by : tests/08-build-vextreme.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     per-page dark CSS added to any page:
 *       - no JS change needed here — the mechanism already sets data-theme="dark"/"light" on <html>; a page's own CSS keys off that attribute
 * LATTICE:END
 */

(function () {
  'use strict';

  var LS_THEME = 'vex-theme';

  function currentTheme() {
    var t = document.documentElement.getAttribute('data-theme');
    return (t === 'dark') ? 'dark' : 'light';
  }

  function iconFor(theme) {
    return theme === 'dark' ? '🌙' : '☀️';
  }

  function applyTheme(theme) {
    document.documentElement.setAttribute('data-theme', theme);
    try { localStorage.setItem(LS_THEME, theme); } catch (e) { /* storage unavailable */ }
  }

  function injectStandaloneStyles() {
    var css = [
      '#vex-theme-fab {',
      '  position: fixed;',
      '  top: 16px;',
      '  right: 120px;',
      '  z-index: 9999;',
      '}',
      '#vex-theme-fab-btn {',
      '  width: 44px;',
      '  height: 44px;',
      '  border-radius: 50%;',
      '  border: none;',
      '  background: rgba(255,255,255,0.18);',
      '  backdrop-filter: blur(6px);',
      '  -webkit-backdrop-filter: blur(6px);',
      '  font-size: 20px;',
      '  cursor: pointer;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  box-shadow: 0 2px 8px rgba(0,0,0,0.12);',
      '  transition: background 0.2s;',
      '  line-height: 1;',
      '  padding: 0;',
      '}',
      '#vex-theme-fab-btn:hover { background: rgba(255,255,255,0.32); }',
    ].join('\n');
    var style = document.createElement('style');
    style.textContent = css;
    document.head.appendChild(style);
  }

  function injectGroupOrbStyles() {
    var css = [
      '.vex-orb {',
      '  width: 40px;',
      '  height: 40px;',
      '  border-radius: 50%;',
      '  border: none;',
      '  flex: 0 0 auto;',
      '  background: rgba(255,255,255,0.18);',
      '  backdrop-filter: blur(6px);',
      '  -webkit-backdrop-filter: blur(6px);',
      '  font-size: 18px;',
      '  cursor: pointer;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  box-shadow: 0 2px 8px rgba(0,0,0,0.12);',
      '  transition: background 0.2s;',
      '  line-height: 1;',
      '  padding: 0;',
      '  text-decoration: none;',
      '  color: inherit;',
      '}',
      '.vex-orb:hover { background: rgba(255,255,255,0.32); }',
    ].join('\n');
    var style = document.createElement('style');
    style.textContent = css;
    document.head.appendChild(style);
  }

  function mount() {
    var saved = 'light';
    try { saved = localStorage.getItem(LS_THEME) || 'light'; } catch (e) {}
    applyTheme(saved);

    var group = document.getElementById('vex-spiral-group');

    var btn = document.createElement('button');
    btn.setAttribute('aria-label', 'Toggle dark / light theme');
    btn.setAttribute('title', 'Toggle theme');
    btn.textContent = iconFor(saved);

    btn.addEventListener('click', function (e) {
      e.stopPropagation();
      var next = currentTheme() === 'dark' ? 'light' : 'dark';
      applyTheme(next);
      btn.textContent = iconFor(next);
    });

    if (group) {
      injectGroupOrbStyles();
      btn.className = 'vex-orb';
      btn.id = 'vex-theme-orb';
      group.appendChild(btn);
      return;
    }

    // Standalone fallback — no #vex-spiral-group on this page.
    injectStandaloneStyles();
    btn.id = 'vex-theme-fab-btn';
    var container = document.createElement('div');
    container.id = 'vex-theme-fab';
    container.appendChild(btn);
    document.body.appendChild(container);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }

}());

// [VXG RealForever]
