/**
 * VEXTREME — widgets/fab-map.js
 *
 * Orb linking to pages/terrain-map.html — the system-health/dependency map,
 * not widgets/fab-demo.js's older "architecture demo" concept (Session 025:
 * the demo page is becoming outdated as the real production system — the
 * terrain map itself — demonstrates the architecture better than a
 * condensed stand-in page).
 *
 * Mounts an orb into #vex-spiral-group if present (Session 025's FAB
 * unification — see widgets/vex-fab.js), else falls back to its own
 * top-level fixed-position button for standalone/pre-spiral-fab use.
 *
 * Self-contained IIFE — no global exports, no framework dependencies.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : orb linking to pages/terrain-map.html
 *   reads     : (none)
 *   writes    : (none)
 *   loaded-by : lib/build-vextreme.js (inlined as map feature in God Scripts)
 *               tests/08-build-vextreme.test.js
 *   tested-by : tests/08-build-vextreme.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 * LATTICE:END
 */

(function () {
  'use strict';

  var MAP_URL = 'https://vgong24.github.io/Vextreme/pages/terrain-map.html';

  function injectStandaloneStyles() {
    var css = [
      '#vex-map-fab {',
      '  position: fixed;',
      '  top: 16px;',
      '  right: 68px;',
      '  z-index: 9999;',
      '}',
      '#vex-map-fab-btn {',
      '  width: 44px;',
      '  height: 44px;',
      '  border-radius: 50%;',
      '  border: none;',
      '  background: rgba(255,255,255,0.18);',
      '  backdrop-filter: blur(6px);',
      '  -webkit-backdrop-filter: blur(6px);',
      '  font-size: 18px;',
      '  cursor: pointer;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  box-shadow: 0 2px 8px rgba(0,0,0,0.12);',
      '  transition: background 0.2s;',
      '  line-height: 1;',
      '  padding: 0;',
      '  text-decoration: none;',
      '  color: inherit;',
      '}',
      '#vex-map-fab-btn:hover { background: rgba(255,255,255,0.32); }',
    ].join('\n');
    var style = document.createElement('style');
    style.textContent = css;
    document.head.appendChild(style);
  }

  function injectGroupOrbStyles() {
    // Shared .vex-orb rule — safe to inject redundantly if fab-theme.js
    // already did (identical CSS text, same specificity, no conflict).
    var css = [
      '.vex-orb {',
      '  width: 40px;',
      '  height: 40px;',
      '  border-radius: 50%;',
      '  border: none;',
      '  flex: 0 0 auto;',
      '  background: rgba(255,255,255,0.18);',
      '  backdrop-filter: blur(6px);',
      '  -webkit-backdrop-filter: blur(6px);',
      '  font-size: 18px;',
      '  cursor: pointer;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  box-shadow: 0 2px 8px rgba(0,0,0,0.12);',
      '  transition: background 0.2s;',
      '  line-height: 1;',
      '  padding: 0;',
      '  text-decoration: none;',
      '  color: inherit;',
      '}',
      '.vex-orb:hover { background: rgba(255,255,255,0.32); }',
    ].join('\n');
    var style = document.createElement('style');
    style.textContent = css;
    document.head.appendChild(style);
  }

  function mount() {
    var group = document.getElementById('vex-spiral-group');

    var btn = document.createElement('a');
    btn.href = MAP_URL;
    btn.setAttribute('aria-label', 'Terrain map — system health & dependencies');
    btn.setAttribute('title', 'Terrain map');
    btn.textContent = '🗺️';

    if (group) {
      injectGroupOrbStyles();
      btn.className = 'vex-orb';
      btn.id = 'vex-map-orb';
      group.appendChild(btn);
      return;
    }

    // Standalone fallback — no #vex-spiral-group on this page.
    injectStandaloneStyles();
    btn.id = 'vex-map-fab-btn';
    var container = document.createElement('div');
    container.id = 'vex-map-fab';
    container.appendChild(btn);
    document.body.appendChild(container);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }

}());

// [VXG RealForever]
