/**
 * VEXTREME — widgets/fab-lang.js
 *
 * Floating language-selector button. Determines the language list to offer
 * from, in order: window.VEX_SUPPORTED_LANGS (baked in at build time by
 * lib/build-vextreme.js — the ground truth for what THIS page's God Script
 * actually has), then a cached index.json blob in localStorage, then a live
 * fetch of index.json. Shows only when 2 or more languages are available.
 * Opens an iOS-style scroll wheel of emoji flags; picking a flag swaps all
 * [data-i18n] elements on the page and persists the choice to localStorage.
 *
 * God Script optimization: if window.VEX_STRINGS_EN is set (inlined at build
 * time by lib/build-vextreme.js), EN strings are used directly without a fetch.
 * JA and other languages are still fetched lazily on first switch.
 *
 * Self-contained IIFE — no global exports, no framework dependencies.
 * Works standalone as a <script> tag or bundled inside a God Script.
 *
 * Session 025 FAB unification: mounts its orb into #vex-spiral-group if
 * present (widgets/vex-fab.js's shared expandable group — real-estate
 * preference is nested, not a separate always-visible sibling FAB), else
 * falls back to the original standalone top-level fixed-position mount.
 * The wheel popup itself is unchanged either way.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : browser language switcher FAB — fetches JA/ZH scope or arc bundles, applies [data-i18n] swaps
 *   reads     : window.VEX_STRING_SCOPES
 *               window.VEX_STRING_CATEGORY
 *               window.VEX_SUPPORTED_LANGS
 *               window.VEX_STRING_ARC_BUNDLE (arc-chunked bundling pilot, checked before the scope path)
 *               data/strings/compiled/scopes/{category}/{scope}.{lang}.json via CDN
 *               data/strings/compiled/arcs/{arc}.{lang}.json via CDN (when VEX_STRING_ARC_BUNDLE is set)
 *               localStorage (LS_LANG — the selected language preference only, not fetched string content)
 *               DOM: #vex-spiral-group (widgets/vex-fab.js — Session 025 FAB unification, nests its orb there if present)
 *               location.search (?lang= param — explicit override for the effective language, wins over localStorage)
 *   writes    : innerHTML / textContent of [data-i18n] elements
 *               localStorage (LS_LANG — selected language preference)
 *               location/history (history.replaceState — reflects the effective language into ?lang= so the current URL is always forwardable)
 *   loaded-by : lib/build-vextreme.js (inlined as lang feature in God Scripts)
 *               legacy pages via direct CDN script tag (pre-God-Script pattern)
 *   tested-by : tests/08-build-vextreme.test.js (structural guard: loadSupportedLangs() must read window.VEX_SUPPORTED_LANGS)
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     arc-chunked bundling pilot (VEX_STRING_ARC_BUNDLE, od-001/td-006):
 *       - lib/build-arc-bundles.js (writes the bundle this fetches)
 *       - lib/build-vextreme.js (emits the global this reads)
 *       - lib/build-sw.js (precaches the arc bundle URLs for opted-in arcs)
 *     scope bundle URL construction:
 *       - lib/strings-compile.js (must write to same path)
 *       - lib/vex-config.js scopeRelPath() (canonical rule)
 *     localStorage key format:
 *       - widgets/sw-register.js (Service Worker pre-caches these URLs)
 *       - any future offline FAB that reads cache state (pe-008)
 *     VEX_* global names read:
 *       - lib/build-vextreme.js assembleGodScript() (must emit matching global names)
 *     URL ?lang= param name:
 *       - any future feature that reads/writes page query params — must not collide with 'lang'; grep pages∕*.html for location.search/URLSearchParams usage before introducing a new param name
 * LATTICE:END
 */

(function () {
  'use strict';

  // Auto-incremented by lib/bump-fab-version.js on every push to main (see
  // .github/workflows/build-index.yml) — do not hand-edit. It cache-busts
  // both this file's script-tag CDN URL indirectly (a version bump means a
  // new commit lands, which is the actual trigger a human/CI would purge
  // on) and, directly, the internal index.json fetch below. Session 025:
  // this constant had never been bumped since introduction, which is most
  // of why a real fix here silently didn't reach CDN-script-tag pages —
  // see docs/lattice-map.json's context note on this file for the story.
  var VERSION    = '2.0.3';
  var CDN_BASE   = 'https://cdn.jsdelivr.net/gh/vgong24/vextreme@main';
  var INDEX_URL  = CDN_BASE + '/data/index.json?v=' + VERSION;
  var LS_LANG    = 'vex-lang';
  var LS_DATA    = 'vex-index-v2-data';

  // ── Config constants (mirrors lib/vex-config.js) ─────────────────────────────
  var CATEGORY_SYSTEM     = 'system';
  var CATEGORY_PRODUCTION = 'production';
  var SCOPE_COMMON        = 'common';
  var LANG_DEFAULT        = 'en';

  // Wheel sizing (Session 025 continued — overflow peek affordance). Full
  // items visible at once before the wheel starts clipping the trailing item
  // into a partial "there's more, scroll" peek. Set to 2 deliberately while
  // this system only ships 3 languages (en/ja/zh) — that's the minimum count
  // where the peek behavior is actually exercised and can be verified live,
  // rather than sized for a 5-language future that doesn't exist yet. Raise
  // toward 5 as more languages ship and 2 stops being a meaningful test of
  // the affordance; the constant is the single place that needs to change.
  var WHEEL_VISIBLE_ITEMS = 2;
  var WHEEL_ITEM_HEIGHT   = 52;
  var WHEEL_PEEK_FRACTION = 0.5;

  var _logger = (window.VEXTREME_LOGGER) || {
    warn:  function(e) { console.warn('[' + e.code + ']', e.message, e); },
    error: function(e) { console.error('[' + e.code + ']', e.message, e); },
  };

  // ── Lang → flag emoji map ────────────────────────────────────────────────────

  var LANG_FLAGS = {
    en: '🇺🇸',
    ja: '🇯🇵',
    es: '🇪🇸',
    fr: '🇫🇷',
    de: '🇩🇪',
    pt: '🇧🇷',
    zh: '🇨🇳',
    ko: '🇰🇷',
    ar: '🇸🇦',
    hi: '🇮🇳',
  };

  function flagFor(lang) {
    return LANG_FLAGS[lang] || '🏳';
  }

  var URL_LANG_PARAM = 'lang';

  // computeLangSearch — pure query-string logic, kept separate from the
  // location/history side effects below so it's directly testable. Given the
  // current `location.search` string and a target language, returns the new
  // search string: the default language (English) is represented by the
  // param's ABSENCE, so a shared link for the common case stays clean, and
  // any other language is explicit — the whole point being that pasting the
  // resulting URL to someone else reproduces the same language without them
  // needing to touch the language wheel at all.
  function computeLangSearch(currentSearch, lang) {
    var params = new URLSearchParams(currentSearch);
    if (lang === LANG_DEFAULT) {
      params.delete(URL_LANG_PARAM);
    } else {
      params.set(URL_LANG_PARAM, lang);
    }
    return params.toString();
  }

  // getUrlLang — reads ?lang= from the current address, if present. Returns
  // null on anything unusable (no URLSearchParams support, sandboxed
  // context) rather than throwing, since this is a nice-to-have, not
  // load-bearing for the widget to function.
  function getUrlLang() {
    try {
      return new URLSearchParams(location.search).get(URL_LANG_PARAM);
    } catch (e) {
      return null;
    }
  }

  // syncUrlLang — reflects the given language into the address bar via
  // replaceState (not pushState — switching languages shouldn't fill the
  // back-button history with one entry per flag tapped). Preserves every
  // other query param and the hash untouched.
  function syncUrlLang(lang) {
    try {
      var newSearch = computeLangSearch(location.search, lang);
      var newUrl = location.pathname + (newSearch ? '?' + newSearch : '') + location.hash;
      var oldUrl = location.pathname + location.search + location.hash;
      if (newUrl !== oldUrl && history.replaceState) {
        history.replaceState(null, '', newUrl);
      }
    } catch (e) { /* URL/History API unavailable or restricted */ }
  }

  // English display names, used only to sort the wheel — not shown as text
  // anywhere (the wheel is flag-only). English itself is pinned first
  // regardless of alphabetical order since it's this system's primary
  // language, not because it sorts first.
  var LANG_NAMES = {
    en: 'English',
    ar: 'Arabic',
    zh: 'Chinese',
    fr: 'French',
    de: 'German',
    hi: 'Hindi',
    ja: 'Japanese',
    ko: 'Korean',
    pt: 'Portuguese',
    es: 'Spanish',
  };

  // sortLangs — English first (primary language, not alphabetical), every
  // other supported language alphabetical by English display name after it.
  // Keeps wheel order stable and predictable as more languages ship, rather
  // than reflecting data/index.json's incidental array order.
  function sortLangs(langs) {
    var rest = langs.filter(function (l) { return l !== LANG_DEFAULT; });
    rest.sort(function (a, b) {
      return (LANG_NAMES[a] || a).localeCompare(LANG_NAMES[b] || b);
    });
    if (langs.indexOf(LANG_DEFAULT) === -1) return rest;
    return [LANG_DEFAULT].concat(rest);
  }

  // ── Index loading (God Script global first, then cache, then network) ────────
  //
  // God Script optimization: lib/build-vextreme.js bakes window.VEX_SUPPORTED_LANGS
  // in at build time (same pattern as window.VEX_STRINGS_EN) — the exact list this
  // page's God Script was actually assembled with. Checking it first means the FAB
  // never depends on a same-origin localStorage blob written by a DIFFERENT widget
  // (vextreme-index-v2.js) or a live index.json fetch that could be stale or slow —
  // both of which can silently omit a language this page genuinely has (e.g. a
  // browser that cached vex-index-v2-data before a language was added never sees
  // it added until that cache key happens to be overwritten by something else).

  function loadSupportedLangs(onReady) {
    if (window.VEX_SUPPORTED_LANGS && window.VEX_SUPPORTED_LANGS.length) {
      onReady(window.VEX_SUPPORTED_LANGS);
      return;
    }

    // Cache is fallback only; a stale index cache must not hide new languages.
    var cachedLangs = null;
    try {
      var raw = localStorage.getItem(LS_DATA);
      if (raw) {
        var cached = JSON.parse(raw);
        if (cached.supportedLangs && cached.supportedLangs.length) {
          cachedLangs = cached.supportedLangs;
        }
      }
    } catch (e) { /* storage unavailable */ }

    var req = new XMLHttpRequest();
    req.open('GET', INDEX_URL, true);
    req.onload = function () {
      if (req.status === 200) {
        try {
          var data = JSON.parse(req.responseText);
          onReady(data.supportedLangs || [LANG_DEFAULT]);
        } catch (e) {
          _logger.warn({ code: 'LANG_FAB_INDEX_PARSE_FAILED', message: 'Failed to parse index.json for lang list' });
          onReady(cachedLangs || [LANG_DEFAULT]);
        }
      } else {
        _logger.warn({ code: 'LANG_FAB_INDEX_HTTP_ERROR', message: 'index.json returned HTTP ' + req.status, status: req.status });
        onReady(cachedLangs || [LANG_DEFAULT]);
      }
    };
    req.onerror = function () {
      _logger.warn({ code: 'LANG_FAB_INDEX_FETCH_FAILED', message: 'Failed to fetch index.json for lang list' });
      onReady(cachedLangs || [LANG_DEFAULT]);
    };
    req.send();
  }

  // ── Strings loading ──────────────────────────────────────────────────────────
  //
  // When window.VEX_STRINGS_EN is set (God Script build-time inline), EN strings
  // are used directly — zero fetch for the default language. JA and other
  // languages are fetched lazily on first switch, same as before.
  //
  // When VEX_STRINGS_EN is absent (standalone <script> tag usage), all languages
  // fetch from CDN. Behavior is identical to pre-God-Script lang-fab.js.

  var _langStrings = {};

  function scopeUrl(scope, lang, category, variant) {
    var cat      = (scope === SCOPE_COMMON) ? CATEGORY_SYSTEM : (category || CATEGORY_PRODUCTION);
    var segments = scope.split('.');
    var dirParts = [cat].concat(segments.slice(0, -1));
    var baseName = segments[segments.length - 1] + (variant ? '.variant-' + variant : '');
    return CDN_BASE + '/data/strings/compiled/scopes/' + dirParts.join('/') + '/' + baseName + '.' + lang + '.json?v=' + VERSION;
  }

  function fetchJSON(url, onDone) {
    var req = new XMLHttpRequest();
    req.open('GET', url, true);
    req.onload = function () {
      if (req.status === 200) {
        try { onDone(null, JSON.parse(req.responseText)); }
        catch (e) { onDone(e); }
      } else {
        onDone(new Error('HTTP ' + req.status));
      }
    };
    req.onerror = function () { onDone(new Error('network error')); };
    req.send();
  }

  function loadStringsForLang(lang, onReady) {
    // God Script optimization: EN strings inlined at build time — no fetch needed.
    if (lang === LANG_DEFAULT && window.VEX_STRINGS_EN) {
      _langStrings = window.VEX_STRINGS_EN;
      onReady();
      return;
    }

    // Arc-chunked bundling pilot (od-001/td-006): one merged fetch per language
    // instead of an N-way scope fan-out. Checked before the scope path so an
    // opted-in arc never touches the per-scope fetch at all. Pages that don't
    // set this global are completely unaffected — see docs/architecture/06-i18n.md.
    var arcBundle = window.VEX_STRING_ARC_BUNDLE;
    if (arcBundle) {
      var arcUrl = CDN_BASE + '/data/strings/compiled/arcs/' + arcBundle + '.' + lang + '.json?v=' + VERSION;
      fetchJSON(arcUrl, function (err, data) {
        if (err) {
          _logger.warn({ code: 'LANG_FAB_ARC_BUNDLE_FETCH_FAILED', message: 'Failed to fetch arc bundle for ' + lang, arc: arcBundle, lang: lang, error: String(err) });
        } else {
          _langStrings = data;
        }
        onReady();
      });
      return;
    }

    var scopes = window.VEX_STRING_SCOPES;

    if (!scopes || !scopes.length) {
      // Legacy / default path — flat bundle fetch.
      var url = CDN_BASE + '/data/strings/compiled/strings.' + lang + '.json?v=' + VERSION;
      fetchJSON(url, function (err, data) {
        if (err) {
          _logger.warn({ code: 'LANG_FAB_STRINGS_FETCH_FAILED', message: 'Failed to fetch strings for ' + lang, lang: lang, error: String(err) });
        } else {
          _langStrings = data;
        }
        onReady();
      });
      return;
    }

    // Scoped path — always include 'common', dedupe, fetch in parallel.
    var variant  = window.VEX_STRING_VARIANT;
    var category = window.VEX_STRING_CATEGORY || CATEGORY_PRODUCTION;
    var wanted   = scopes.indexOf(SCOPE_COMMON) === -1 ? [SCOPE_COMMON].concat(scopes) : scopes.slice();
    var merged   = {};
    var remaining = wanted.length;

    if (!remaining) { onReady(); return; }

    wanted.forEach(function (scope) {
      var url = scopeUrl(scope, lang, category, variant);

      fetchJSON(url, function (err, data) {
        if (err && variant) {
          var baseUrl = scopeUrl(scope, lang, category);
          fetchJSON(baseUrl, function (baseErr, baseData) {
            if (!baseErr) Object.keys(baseData).forEach(function (k) { merged[k] = baseData[k]; });
            else _logger.warn({ code: 'LANG_FAB_STRINGS_HTTP_ERROR', message: 'scope bundle missing for ' + scope, lang: lang, scope: scope });
            if (--remaining === 0) { _langStrings = merged; onReady(); }
          });
          return;
        }
        if (err) {
          _logger.warn({ code: 'LANG_FAB_STRINGS_HTTP_ERROR', message: 'scope bundle missing for ' + scope, lang: lang, scope: scope });
        } else {
          Object.keys(data).forEach(function (k) { merged[k] = data[k]; });
        }
        if (--remaining === 0) { _langStrings = merged; onReady(); }
      });
    });
  }

  // ── i18n swap ────────────────────────────────────────────────────────────────

  function applyLang(lang) {
    loadStringsForLang(lang, function () {
      var els = document.querySelectorAll('[data-i18n]');
      for (var i = 0; i < els.length; i++) {
        var key   = els[i].getAttribute('data-i18n');
        var entry = _langStrings[key];
        if (entry && entry.text) {
          els[i].textContent = entry.text;
        }
      }
      try { localStorage.setItem(LS_LANG, lang); } catch (e) {}
    });
  }

  // ── FAB DOM + styles ─────────────────────────────────────────────────────────

  function injectStyles() {
    var css = [
      '#vex-lang-fab {',
      '  position: fixed;',
      '  top: 16px;',
      '  right: 16px;',
      '  z-index: 9999;',
      '  font-family: inherit;',
      '}',
      // Session 025 FAB unification: when mounted inside #vex-spiral-group
      // (widgets/vex-fab.js) instead of standalone, drop the fixed
      // positioning and let the group's flex layout place the orb — the
      // wheel below still anchors correctly since it's absolutely
      // positioned relative to THIS container, whichever mode is active.
      '#vex-lang-fab.vex-nested {',
      '  position: relative;',
      '  top: auto;',
      '  right: auto;',
      '  z-index: auto;',
      '}',
      '#vex-lang-fab-btn {',
      '  width: 44px;',
      '  height: 44px;',
      '  border-radius: 50%;',
      '  border: none;',
      '  background: rgba(255,255,255,0.18);',
      '  backdrop-filter: blur(6px);',
      '  -webkit-backdrop-filter: blur(6px);',
      '  font-size: 24px;',
      '  cursor: pointer;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  box-shadow: 0 2px 8px rgba(0,0,0,0.12);',
      '  transition: background 0.2s;',
      '  line-height: 1;',
      '  padding: 0;',
      '}',
      '#vex-lang-fab-btn:hover { background: rgba(255,255,255,0.32); }',
      '#vex-lang-wheel {',
      '  position: absolute;',
      '  top: 52px;',
      '  right: 0;',
      '  width: 60px;',
      '  overflow: hidden;',
      '  display: none;',
      '  border-radius: 12px;',
      '  background: rgba(255,255,255,0.15);',
      '  backdrop-filter: blur(10px);',
      '  -webkit-backdrop-filter: blur(10px);',
      '  box-shadow: 0 4px 24px rgba(0,0,0,0.18);',
      '}',
      '#vex-lang-wheel.open { display: block; }',
      // Overflow peek affordance (Session 025 continued): when more languages
      // exist than fit in the visible window, the wheel's own height clips the
      // trailing item to a fraction — a visibly cut-off flag reads as "more
      // below, scroll" far more reliably than the old fully-opaque single-item
      // wheel did, which showed one flag at a time with no indication siblings
      // existed. This gradient only softens the very top/bottom edges now
      // (short fade, not a near-opaque cap) so a peeked item stays recognizable
      // rather than being masked into a blank sliver.
      '#vex-lang-wheel-mask {',
      '  position: absolute;',
      '  inset: 0;',
      '  pointer-events: none;',
      '  z-index: 2;',
      '  background: linear-gradient(',
      '    to bottom,',
      '    rgba(255,255,255,0.35) 0%,',
      '    transparent 12%,',
      '    transparent 88%,',
      '    rgba(255,255,255,0.35) 100%',
      '  );',
      '}',
      '#vex-lang-wheel-track {',
      '  position: absolute;',
      '  inset: 0;',
      '  overflow-y: auto;',
      '  scroll-snap-type: y proximity;',
      '  -webkit-overflow-scrolling: touch;',
      '  scrollbar-width: none;',
      '}',
      '#vex-lang-wheel-track::-webkit-scrollbar { display: none; }',
      '.vex-lang-item {',
      '  height: 52px;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  font-size: 28px;',
      '  scroll-snap-align: start;',
      '  cursor: pointer;',
      '  transition: opacity 0.15s;',
      '  line-height: 1;',
      '}',
      '.vex-lang-item:hover { opacity: 0.7; }',
      '.vex-lang-item.vex-lang-current { background: rgba(255,255,255,0.25); }',
    ].join('\n');

    var style = document.createElement('style');
    style.textContent = css;
    document.head.appendChild(style);
  }

  function buildFAB(langs, currentLang) {
    var container = document.createElement('div');
    container.id = 'vex-lang-fab';

    var btn = document.createElement('button');
    btn.id = 'vex-lang-fab-btn';
    btn.setAttribute('aria-label', 'Select language');
    btn.textContent = flagFor(currentLang);

    var wheel = document.createElement('div');
    wheel.id = 'vex-lang-wheel';

    // Overflow peek: show WHEEL_VISIBLE_ITEMS full rows; if there are more
    // languages than that, clip the wheel's height mid-row so the next item
    // is visibly cut off (a "peek") instead of hidden entirely — the visual
    // signal that more languages are reachable by scrolling. When everything
    // fits, no clipping happens and there's nothing to scroll.
    var visibleItems = Math.min(langs.length, WHEEL_VISIBLE_ITEMS);
    var hasOverflow   = langs.length > visibleItems;
    var wheelHeight   = (hasOverflow ? visibleItems + WHEEL_PEEK_FRACTION : visibleItems) * WHEEL_ITEM_HEIGHT;
    wheel.style.height = wheelHeight + 'px';

    var mask = document.createElement('div');
    mask.id = 'vex-lang-wheel-mask';

    var track = document.createElement('div');
    track.id = 'vex-lang-wheel-track';

    for (var i = 0; i < langs.length; i++) {
      (function (lang) {
        var item = document.createElement('div');
        item.className = 'vex-lang-item' + (lang === currentLang ? ' vex-lang-current' : '');
        item.textContent = flagFor(lang);
        item.setAttribute('data-lang', lang);
        item.setAttribute('title', lang);
        item.addEventListener('click', function () {
          btn.textContent = flagFor(lang);
          wheel.classList.remove('open');
          syncUrlLang(lang);
          if (lang !== currentLang) {
            currentLang = lang;
            applyLang(lang);
          }
        });
        track.appendChild(item);
      })(langs[i]);
    }

    wheel.appendChild(mask);
    wheel.appendChild(track);
    container.appendChild(btn);
    container.appendChild(wheel);

    btn.addEventListener('click', function (e) {
      e.stopPropagation();
      wheel.classList.toggle('open');
    });

    document.addEventListener('click', function () {
      wheel.classList.remove('open');
    });

    return container;
  }

  // ── Mount ─────────────────────────────────────────────────────────────────────

  function mount() {
    loadSupportedLangs(function (langs) {
      // Mount even with a single language (previously skipped when
      // langs.length < 2). Per Victor, 2026-07-10: "the language even if
      // just 1, should still be there" — the orb is part of the consistent
      // FAB chrome, and hiding it made the whole spiral look broken on
      // pages/environments where the supported-langs fetch fell back to
      // the single default. With one language the wheel simply shows the
      // current language; selecting it is a no-op.
      if (!langs || !langs.length) return;
      langs = sortLangs(langs);

      var savedLang = LANG_DEFAULT;
      try { savedLang = localStorage.getItem(LS_LANG) || LANG_DEFAULT; } catch (e) {}

      // A ?lang= in the URL wins over the stored preference — this is what
      // makes a shared link actually reproducible: someone forwarding a page
      // with ?lang=zh should not need the recipient to already have zh saved
      // locally, or to find the language wheel and pick it themselves.
      var urlLang = getUrlLang();
      if (urlLang && langs.indexOf(urlLang) >= 0) {
        savedLang = urlLang;
        try { localStorage.setItem(LS_LANG, savedLang); } catch (e) {}
      }

      if (langs.indexOf(savedLang) < 0) savedLang = langs[0];

      // Reflect the effective language into the URL even when it came from
      // localStorage, not the querystring — so the address bar is always an
      // accurate, forwardable snapshot of what's currently on screen, not
      // only right after a manual language switch.
      syncUrlLang(savedLang);

      injectStyles();
      var fab = buildFAB(langs, savedLang);

      // Session 025 FAB unification: nest into the shared spiral-fab group
      // if present (widgets/vex-fab.js), else keep the original standalone
      // top-level mount — real-estate preference is nested, not sibling,
      // but standalone must keep working for any page without spiral-fab.
      var group = document.getElementById('vex-spiral-group');
      if (group) {
        fab.classList.add('vex-nested');
        group.appendChild(fab);
      } else {
        document.body.appendChild(fab);
      }

      // Apply persisted lang on load (skip if already English — avoids a
      // pointless fetch when no preference has been set)
      if (savedLang !== LANG_DEFAULT) applyLang(savedLang);
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }

}());

// [VXG RealForever]
