/**
 * VEXTREME — widgets/vex-fab.js
 *
 * Spiral FAB — the single expandable trigger that replaces one-off,
 * separately-positioned orb widgets. Renders a trigger button (🌀) that
 * toggles a shared group container (#vex-spiral-group); other feature
 * widgets (fab-theme.js, fab-map.js, fab-lang.js) each mount their own orb
 * INTO that container on their own DOMContentLoaded handler, rather than
 * creating their own top-level fixed-position FAB. This is the "pattern for
 * expansion" Session 025 asked for: a new orb is a new small widget that
 * looks for #vex-spiral-group and appends into it if present — this file
 * does not need to change when an orb is added or removed.
 *
 * Deliberately NOT a generic "action vs expandable" component framework —
 * each orb widget still owns its own DOM/behavior/styles. This file's only
 * job is the trigger + group container + open/close state. See each orb
 * widget's own docstring for its mount-into-group contract.
 *
 * Self-contained IIFE — no global exports, no framework dependencies.
 * Works standalone as a <script> tag or bundled inside a God Script.
 * Must be the FIRST fab-group feature listed in lib/build-vextreme.js's
 * FEATURES registry — see the comment there for why registration order
 * matters (DOMContentLoaded handlers fire in the order they're added).
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : spiral FAB — trigger button + shared expandable group container that other orb widgets mount into
 *   reads     : (none)
 *   writes    : DOM: #vex-spiral-fab / #vex-spiral-trigger / #vex-spiral-group (consumed by fab-lang.js, fab-theme.js, fab-map.js)
 *   loaded-by : lib/build-vextreme.js (inlined as spiral-fab feature in God Scripts, must be first among the FAB-group features)
 *               tests/08-build-vextreme.test.js
 *   tested-by : tests/08-build-vextreme.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     #vex-spiral-group DOM id/contract changed:
 *       - widgets/fab-lang.js (getElementById('vex-spiral-group') lookup)
 *       - widgets/fab-theme.js (getElementById('vex-spiral-group') lookup)
 *       - widgets/fab-map.js (getElementById('vex-spiral-group') lookup)
 *       - tests/08 (FAB SYSTEM: nesting assertions)
 * LATTICE:END
 */

(function () {
  'use strict';

  var LS_OPEN = 'vex-spiral-open'; // not persisted across page loads on purpose — every page starts closed

  function injectStyles() {
    var css = [
      '#vex-spiral-fab {',
      '  position: fixed;',
      '  top: 16px;',
      '  right: 16px;',
      '  z-index: 9998;', // one below any orb's own popup (e.g. the lang wheel) so it never occludes them
      '  display: flex;',
      '  align-items: flex-start;',
      '  gap: 8px;',
      '  font-family: inherit;',
      '}',
      '#vex-spiral-trigger {',
      '  width: 44px;',
      '  height: 44px;',
      '  border-radius: 50%;',
      '  border: none;',
      '  flex: 0 0 auto;',
      '  background: rgba(255,255,255,0.18);',
      '  backdrop-filter: blur(6px);',
      '  -webkit-backdrop-filter: blur(6px);',
      '  font-size: 20px;',
      '  cursor: pointer;',
      '  display: flex;',
      '  align-items: center;',
      '  justify-content: center;',
      '  box-shadow: 0 2px 8px rgba(0,0,0,0.12);',
      '  transition: background 0.2s, transform 0.2s;',
      '  line-height: 1;',
      '  padding: 0;',
      '}',
      '#vex-spiral-trigger:hover { background: rgba(255,255,255,0.32); }',
      '#vex-spiral-trigger.open { transform: rotate(90deg); }',
      '#vex-spiral-group {',
      '  display: none;',
      '  align-items: center;',
      '  gap: 8px;',
      '  flex-wrap: wrap;',
      '  max-width: 220px;',
      '}',
      '#vex-spiral-group.open { display: flex; }',
    ].join('\n');

    var style = document.createElement('style');
    style.textContent = css;
    document.head.appendChild(style);
  }

  function mount() {
    injectStyles();

    var container = document.createElement('div');
    container.id = 'vex-spiral-fab';

    var trigger = document.createElement('button');
    trigger.id = 'vex-spiral-trigger';
    trigger.setAttribute('aria-label', 'Open menu');
    trigger.setAttribute('aria-expanded', 'false');
    trigger.textContent = '🌀';

    var group = document.createElement('div');
    group.id = 'vex-spiral-group';

    trigger.addEventListener('click', function (e) {
      e.stopPropagation();
      var open = group.classList.toggle('open');
      trigger.classList.toggle('open', open);
      trigger.setAttribute('aria-expanded', String(open));
    });

    // Click anywhere outside the group (and not on the trigger) closes it —
    // same convention widgets/fab-lang.js's own wheel already uses.
    document.addEventListener('click', function (e) {
      if (!group.classList.contains('open')) return;
      if (group.contains(e.target) || trigger.contains(e.target)) return;
      group.classList.remove('open');
      trigger.classList.remove('open');
      trigger.setAttribute('aria-expanded', 'false');
    });

    container.appendChild(trigger);
    container.appendChild(group);
    document.body.appendChild(container);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', mount);
  } else {
    mount();
  }

}());

// [VXG RealForever]
