#!/usr/bin/env node
/**
 * VEXTREME — lib/audit-nav.js
 *
 * Read-only auditor: which pages/*.html give a visitor any way to navigate
 * elsewhere in the system, and which are dead ends. Prompted directly by
 * Victor (2026-07-10): "we don't have a fully visible header either on all
 * of these htmls, so i can never navigate to like the main index or the map
 * through FABs that haven't been displayable on any html in Vextreme yet."
 *
 * Three independent navigation mechanisms exist in this repo, none of which
 * reach most pages:
 *   - Static hub links — a page's own raw HTML links directly to at least
 *     one of the real hub destinations (index.html, archives.html,
 *     ecosystem-hub.html, terrain-map.html). archives.html/ecosystem-hub.html
 *     have this baked into their generated markup; most pages don't.
 *   - shell.js (v1) — injects a real, working site-nav bar (lib/vextreme.js's
 *     injectNav()) but only 3 pages reference it.
 *   - God Script FAB navigation (v2) — spiral-fab + map/analysis orbs, but
 *     only pages actually wired to a God Script get it (currently 1 of 39).
 *
 * A page with none of the three is a dead end: a visitor who lands on it has
 * no way to discover the rest of the system exists.
 *
 * Run: node lib/audit-nav.js
 *
 * This script does not change anything. It is read-only, same posture as
 * lib/audit-pages.js.
 *
 * Pure functions exported for testing:
 *   countStaticHubLinks(html) → number
 *   hasShellJs(html) → boolean
 *   godScriptHasSpiralFab(distJs) → boolean
 *   classifyNav(slug, html, wired, distJs) → { slug, staticHubLinks, hasShellJs, hasFabNav, navigable }
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : nav-coverage auditor -- read-only report of which pages∕*.html give a visitor any way to navigate elsewhere in the system
 *   reads     : pages∕*.html (checks for hub links, shell.js reference)
 *               dist∕*.js (checks for spiral-fab feature, only for pages already wired)
 *               lib/audit-pages.js (getPageSlugs, isWiredToGodScript -- reused directly, not duplicated)
 *   writes    : stdout only -- read-only, changes nothing
 *   loaded-by : manual run: node lib/audit-nav.js
 *               tests/38-audit-nav.test.js
 *               lib/build-page-health.js (reuses the navigation report)
 *   tested-by : tests/38-audit-nav.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     HUB_DESTINATIONS changed (a hub page renamed or a new hub page added):
 *       - countStaticHubLinks() here reads this list directly
 *     lib/audit-pages.js isWiredToGodScript()/getPageSlugs() shape changed:
 *       - this file destructures both by name -- a rename there breaks this require
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const { getPageSlugs, isWiredToGodScript } = require('./audit-pages');

const ROOT      = path.join(__dirname, '..');
const PAGES_DIR = path.join(ROOT, 'pages');
const DIST_DIR  = path.join(ROOT, 'dist');

// The real, existing hub destinations a static link could point to. A page
// linking to any one of these gives a visitor at least one way out.
const HUB_DESTINATIONS = ['index.html', 'archives.html', 'ecosystem-hub.html', 'terrain-map.html'];

// ── Pure computation ─────────────────────────────────────────────────────────

// countStaticHubLinks — how many distinct hub destinations this page's raw
// HTML links to, regardless of absolute/relative URL form.
function countStaticHubLinks(html) {
  return HUB_DESTINATIONS.filter(dest => html.includes(dest)).length;
}

// hasShellJs — references the v1 loader (lib/shell.js), which injects a
// real site-nav bar via lib/vextreme.js's injectNav() on load.
function hasShellJs(html) {
  return html.includes('lib/shell.js');
}

// godScriptHasSpiralFab — the assembled God Script bundles spiral-fab (the
// orb-group trigger every other FAB nests into) — a page without this
// feature gets no FAB navigation even if it's wired to a God Script at all.
function godScriptHasSpiralFab(distJs) {
  if (!distJs) return false;
  return distJs.includes('feature: spiral-fab') || distJs.includes('vex-fab.js');
}

// classifyNav — full per-page classification. navigable = true if any of
// the three independent mechanisms gives a visitor a way out.
function classifyNav(slug, html, wired, distJs) {
  const staticHubLinks = countStaticHubLinks(html);
  const shellJs        = hasShellJs(html);
  const fabNav         = wired && godScriptHasSpiralFab(distJs);

  return {
    slug,
    staticHubLinks,
    hasShellJs: shellJs,
    hasFabNav:  fabNav,
    navigable:  staticHubLinks > 0 || shellJs || fabNav,
  };
}

// ── I/O ───────────────────────────────────────────────────────────────────────

function readFileOrEmpty(p) {
  return fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : '';
}

function getNavReport() {
  const rows = getPageSlugs().map(slug => {
    const html   = readFileOrEmpty(path.join(PAGES_DIR, slug + '.html'));
    const wired  = isWiredToGodScript(slug);
    const distJs = wired ? readFileOrEmpty(path.join(DIST_DIR, `vextreme-${slug}.js`)) : '';
    return classifyNav(slug, html, wired, distJs);
  });

  const isolated = rows.filter(r => !r.navigable).map(r => r.slug);

  return {
    rows,
    summary: {
      total:     rows.length,
      navigable: rows.length - isolated.length,
      isolated:  isolated.length,
      isolatedSlugs: isolated,
    },
  };
}

function audit() {
  const { rows, summary } = getNavReport();

  const slugW = Math.max(8, ...rows.map(r => r.slug.length));

  const header = [
    'PAGE'.padEnd(slugW),
    'HUB LINKS'.padEnd(10),
    'SHELL.JS'.padEnd(9),
    'FAB NAV'.padEnd(8),
    'RESULT',
  ].join('  ');
  const divider = '-'.repeat(header.length);

  console.log('\n' + divider);
  console.log(header);
  console.log(divider);

  for (const r of rows) {
    console.log([
      r.slug.padEnd(slugW),
      String(r.staticHubLinks).padEnd(10),
      (r.hasShellJs ? 'YES' : 'no').padEnd(9),
      (r.hasFabNav ? 'YES' : 'no').padEnd(8),
      r.navigable ? 'navigable' : 'ISOLATED — no way out',
    ].join('  '));
  }

  console.log(divider);
  console.log(`\nSummary: ${summary.navigable}/${summary.total} pages navigable, ${summary.isolated} isolated (dead ends)`);
  if (summary.isolated) {
    console.log(`Isolated: ${summary.isolatedSlugs.join(', ')}`);
  }
  console.log('');
}

if (require.main === module) {
  audit();
}

module.exports = { HUB_DESTINATIONS, countStaticHubLinks, hasShellJs, godScriptHasSpiralFab, classifyNav, getNavReport };

// [VXG RealForever]
