#!/usr/bin/env node
/**
 * VEXTREME — lib/audit-pages.js
 *
 * Utility for Claude instances and developers to instantly see which HTML pages
 * are wired to God Scripts, which are not, and why.
 *
 * Run: node lib/audit-pages.js
 *
 * Output columns:
 *   PAGE           — slug (filename without .html)
 *   GOD SCRIPT     — exists in dist/ (YES/NO)
 *   WIRED          — HTML loads from dist/ (YES/NO/SKIP)
 *   STATUS         — ready / blocked (with reason) / skip (generated/v1)
 *
 * "SKIP" means the page intentionally does not follow the God Script pattern:
 *   - generated pages (archives.html, ecosystem-hub.html) have their own loaders
 *   - v1 pages (restoration-protocol.html) use shell.js
 *
 * This script does not change anything. It is read-only.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : page wiring auditor — read-only report of which pages∕*.html are wired to a God Script, blocked, or intentionally skipped
 *   reads     : pages∕*.html (checks for a dist/vextreme-{slug}.js script src)
 *               dist∕*.js (checks which God Scripts exist)
 *               data/index.json
 *   writes    : stdout only — read-only, changes nothing
 *   loaded-by : manual run: node lib/audit-pages.js
 *               CLAUDE.md (points here as the wiring-status source of truth)
 *               lib/check-key-alignment.js (imports SKIP_PAGES + getPageSlugs — reuses the skip list instead of duplicating it)
 *               lib/build-index.js (SKIP_PAGES + getPageSlugs, feeds auto-discovery)
 *               lib/build-archives.js (same, independently — see pe-011)
 *   tested-by : (none)
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     a page becomes wired/unwired:
 *       - SKIP_PAGES or BLOCKERS entry in this file may need updating if the reason changes
 *       - CLAUDE.md 'Current blockers' section (prose summary — keep loosely in sync)
 *     a new generated page added (own loader, not God Script):
 *       - SKIP_PAGES entry — otherwise it reports as a false blocker
 *       - lib/check-key-alignment.js's orphan-page check also reads SKIP_PAGES — a page that's a false positive there is fixed the same way
 *     SKIP_PAGES / getPageSlugs export shape changed:
 *       - lib/check-key-alignment.js (destructures both by name — a rename here breaks that require)
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT      = path.join(__dirname, '..');
const PAGES_DIR = path.join(ROOT, 'pages');
const DIST_DIR  = path.join(ROOT, 'dist');

// Pages that intentionally skip the God Script pattern with a reason.
const SKIP_PAGES = {
  'archives':      'generated page — has its own renderer script, not a God Script consumer',
  'ecosystem-hub': 'generated page — has its own renderer script, not a God Script consumer',
  'roles-index':   'generated page — has its own renderer script, not a God Script consumer',
  'v2-test':       'dev fixture for testing arc nav — no string scopes, not a content page',
};

// Pages blocked from wiring with documented reasons.
const BLOCKERS = {
  'claude-answers-the-doubt':      'has #arcNavMount — vextreme-index-v2.js must be inlined into God Script first',
  'restoration-protocol':          'uses shell.js (v1 path) — needs investigation before porting',
  'specimen-architectural-wisdoms':'no compiled string bundle — hasScopeBundle returns false, build skips it',
};

function getPageSlugs() {
  return fs.readdirSync(PAGES_DIR)
    .filter(f => f.endsWith('.html'))
    .map(f => f.replace(/\.html$/, ''))
    .sort();
}

function godScriptPath(slug) {
  return path.join(DIST_DIR, `vextreme-${slug}.js`);
}

function godScriptExists(slug) {
  return fs.existsSync(godScriptPath(slug));
}

function isWiredToGodScript(slug) {
  const htmlPath = path.join(PAGES_DIR, slug + '.html');
  if (!fs.existsSync(htmlPath)) return false;
  const html = fs.readFileSync(htmlPath, 'utf8');
  const expectedSrc = `dist/vextreme-${slug}.js`;
  return html.includes(expectedSrc);
}

function hasOldPattern(slug) {
  const htmlPath = path.join(PAGES_DIR, slug + '.html');
  if (!fs.existsSync(htmlPath)) return false;
  const html = fs.readFileSync(htmlPath, 'utf8');
  return html.includes('widgets/lang-fab.js') || html.includes('widgets/demo-fab.js');
}

function audit() {
  const slugs = getPageSlugs();

  const rows = [];
  let wiredCount = 0;
  let blockedCount = 0;
  let skipCount = 0;
  let readyCount = 0;

  for (const slug of slugs) {
    const skip    = SKIP_PAGES[slug];
    const blocker = BLOCKERS[slug];
    const exists  = godScriptExists(slug);
    const wired   = isWiredToGodScript(slug);
    const oldPat  = hasOldPattern(slug);

    let status;
    let wiredLabel;

    if (skip) {
      status     = `SKIP — ${skip}`;
      wiredLabel = 'SKIP';
      skipCount++;
    } else if (wired) {
      status     = 'wired';
      wiredLabel = 'YES';
      wiredCount++;
    } else if (blocker) {
      status     = `BLOCKED — ${blocker}`;
      wiredLabel = 'NO';
      blockedCount++;
    } else if (exists && oldPat) {
      status     = 'READY — God Script exists, still using old 3-tag pattern';
      wiredLabel = 'NO';
      readyCount++;
    } else if (exists) {
      status     = 'READY — God Script exists, wiring TBD';
      wiredLabel = 'NO';
      readyCount++;
    } else {
      status     = 'NO GOD SCRIPT — build-vextreme.js skipped this slug';
      wiredLabel = 'NO';
      blockedCount++;
    }

    rows.push({ slug, exists, wiredLabel, status });
  }

  // Print table
  const slugW   = Math.max(8, ...rows.map(r => r.slug.length));
  const existsW = 10;
  const wiredW  = 8;

  const header = [
    'PAGE'.padEnd(slugW),
    'GOD SCRIPT'.padEnd(existsW),
    'WIRED'.padEnd(wiredW),
    'STATUS',
  ].join('  ');

  const divider = '-'.repeat(header.length);

  console.log('\n' + divider);
  console.log(header);
  console.log(divider);

  for (const r of rows) {
    console.log([
      r.slug.padEnd(slugW),
      (r.exists ? 'YES' : 'NO').padEnd(existsW),
      r.wiredLabel.padEnd(wiredW),
      r.status,
    ].join('  '));
  }

  console.log(divider);
  console.log(`\nSummary: ${wiredCount} wired, ${readyCount} ready-to-wire, ${blockedCount} blocked/missing, ${skipCount} skip`);
  console.log('');
}

if (require.main === module) {
  audit();
}

module.exports = { SKIP_PAGES, BLOCKERS, getPageSlugs, godScriptExists, isWiredToGodScript };

// [VXG RealForever]
