#!/usr/bin/env node
/**
 * VEXTREME — lib/build-sitemap.js
 *
 * Generates sitemap.xml at repo root — lists all live pages for crawlers.
 * Only includes pages that actually exist in pages/ (ported nodes).
 * Unported nodes are excluded — no 404s in the sitemap.
 *
 * Run manually:   node lib/build-sitemap.js
 * Auto-run via:   .github/workflows/build-index.yml
 *
 * Sitemap lastmod is intentionally omitted. A generated page's most recent
 * git commit is often the artifact rebuild itself, not a semantic content
 * change; using it makes the sitemap depend on the commit that carries the
 * sitemap and therefore requires another corrective commit. An absent
 * lastmod is more honest than a build clock presented as content freshness.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : generates sitemap.xml — lists only pages that actually exist, so crawlers never hit a 404
 *   reads     : data/nodes.json
 *               pages∕*.html (existence check only, per slug)
 *   writes    : sitemap.xml
 *   loaded-by : .github/workflows/build-index.yml
 *               tests/55-build-sitemap.test.js
 *   tested-by : tests/55-build-sitemap.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     a new utility page added (non-node, not from nodes.json):
 *       - UTILITY_PAGES array in this file — otherwise it's silently excluded from the sitemap
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT      = path.join(__dirname, '..');
const GH_BASE   = 'https://vgong24.github.io/Vextreme/pages';

// ── Pure computation ─────────────────────────────────────────────────────────

function renderSitemap(locations) {
  const urlEntries = locations.map(loc => `  <url>\n    <loc>${loc}</loc>\n  </url>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>`;
}

// ── Collect live pages ────────────────────────────────────────────────────────

// Utility pages to include in sitemap (non-node pages)
const UTILITY_PAGES = ['archives', 'vextreme-demo', 'specimens', 'specimen-full-translation', 'specimen-partial-translation', 'specimen-smallest-miss'];

function collectLiveUrls(root = ROOT) {
  const pagesDir = path.join(root, 'pages');
  const nodes = JSON.parse(fs.readFileSync(path.join(root, 'data', 'nodes.json'), 'utf8'));
  const locations = nodes
    .filter(node => node.id !== null && fs.existsSync(path.join(pagesDir, `${node.slug}.html`)))
    .sort((a, b) => a.id - b.id)
    .map(node => `${GH_BASE}/${node.slug}.html`);

  for (const slug of UTILITY_PAGES) {
    if (fs.existsSync(path.join(pagesDir, `${slug}.html`))) locations.push(`${GH_BASE}/${slug}.html`);
  }
  return locations;
}

// ── Generate XML ──────────────────────────────────────────────────────────────

function run(root = ROOT) {
  const locations = collectLiveUrls(root);
  fs.writeFileSync(path.join(root, 'sitemap.xml'), renderSitemap(locations));
  console.log(`[build-sitemap] Done.`);
  console.log(`  live URLs : ${locations.length}`);
  console.log(`  output    : sitemap.xml`);
  return locations;
}

if (require.main === module) run();

module.exports = { UTILITY_PAGES, collectLiveUrls, renderSitemap, run };

// [VXG RealForever]
