#!/usr/bin/env node
/**
 * VEXTREME — lib/build-status.js
 *
 * Assembles data/status.json — the system health manifest.
 *
 * Six notice categories:
 *   translation     — auto-generated from strings/compiled/manifest.json
 *                     keys missing from any supported language (excluding demo
 *                     category pages where gaps are intentional fixtures)
 *   techDebt        — hand-authored in data/status/tech-debt.json (decided fix, not built)
 *   enhancements    — hand-authored in data/status/planned-enhancements.json (decided direction, not built)
 *   assumptions     — hand-authored in data/status/assumptions.json
 *   openDiscussions — hand-authored in data/status/open-discussions.json (a fork in the
 *                     road where the fork itself hasn't been chosen yet — see that file's
 *                     _comment for how this differs from techDebt/enhancements)
 *   contentIntegrity — auto-generated from lib/check-key-alignment.js: orphan pages
 *                     (a pages/*.html file with no nodes.json entry), wip/ slug
 *                     collisions (a wip/ file's declared _meta.slug already exists
 *                     as a real page), and duplicate wip/ intents (two wip/ files
 *                     declaring the same slug). Informational only — nothing here
 *                     blocks a build; see check-key-alignment.js's own header for why.
 *
 * Also computes lattice coverage (docs/lattice-map.json nodes vs. total eligible
 * .js files in lib/+widgets/) into _meta.lattice, so pages/ecosystem-hub.html can
 * show it without re-deriving the eligibility rule itself.
 *
 * Pure functions exported for testing:
 *   buildTranslationNotices(manifest, flatEnBundle, supportedLangs, demoScopePrefix)
 *   buildStatusRollup(notices, meta)
 *   countOpen(notices)
 *   buildLatticeCoverage(latticeMap, libWidgetsJsFiles)
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : system health manifest assembler — reads hand-authored status∕*.json plus the strings manifest and key-alignment report, writes data/status.json
 *   reads     : data/strings/compiled/manifest.json
 *               data/strings/compiled/strings.en.json
 *               data/index.json
 *               data/strings/compiled/scopes/demo/ (recursive walk for fixture detection)
 *               data/status/tech-debt.json
 *               data/status/planned-enhancements.json
 *               data/status/assumptions.json
 *               data/status/open-discussions.json
 *               docs/lattice-map.json
 *               lib/ and widgets/ directory listings (.js files, for coverage denominator)
 *               lib/check-key-alignment.js (checkKeyAlignment() — orphan pages, wip collisions/duplicate intents)
 *   writes    : data/status.json
 *   loaded-by : pages/ecosystem-hub.html (live fetch)
 *               tests/10-build-status.test.js
 *   tested-by : tests/10-build-status.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     notice category added/removed:
 *       - lib/build-ecosystem-hub.js (render order array + icon map)
 *       - tests/10 (SAMPLE_NOTICES + assertions)
 *     status∕*.json item schema changed:
 *       - lib/build-ecosystem-hub.js renderHealthPanel() (reads title/description/priority/considerations/etc.)
 *       - tests/10 (required-fields integration tests)
 *     lattice coverage eligibility rule changed:
 *       - lib/build-lattice-headers.js isEligibleNode() (must stay identical or the two coverage numbers disagree)
 *     check-key-alignment.js report shape changed:
 *       - buildContentIntegrityNotices() here reads report.pages.orphans / report.wip.collisions / report.wip.duplicateIntents directly — a shape change there breaks this silently unless tests/10 or tests/08 catch it
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT       = path.join(__dirname, '..');
const STATUS_DIR = path.join(ROOT, 'data', 'status');
const STATUS_OUT = path.join(ROOT, 'data', 'status.json');
const COMPILED   = path.join(ROOT, 'data', 'strings', 'compiled');
const INDEX_IN   = path.join(ROOT, 'data', 'index.json');

// ── Pure computation ─────────────────────────────────────────────────────────

/**
 * buildTranslationNotices — finds string keys missing from any supported lang.
 * Demo-category scope keys (pages starting with demoScopePrefix in their scope
 * name where those scopes live under the demo/ compiled dir) are marked
 * intentional: true — they are fixture gaps, not genuine translation debt.
 *
 * Returns an array of notice objects sorted by priority (production first).
 */
function buildTranslationNotices(manifest, flatEnBundle, supportedLangs, demoScopes) {
  const demo  = new Set(demoScopes || []);
  const items = [];

  for (const [key, entry] of Object.entries(manifest)) {
    for (const lang of supportedLangs) {
      if (lang === 'en') continue;
      if (entry.langs.includes(lang)) continue;

      const enVal      = flatEnBundle[key];
      // A key belongs to a demo scope if any demo scope string is a prefix of it.
      // e.g. key 'pages.specimen-partial-translation.body.untranslated'
      //      matches demo scope 'pages.specimen-partial-translation'
      const intentional = [...demo].some(s => key === s || key.startsWith(s + '.'));

      items.push({
        key,
        lang,
        reason:       'missing_translation',
        intentional,
        en: enVal ? (enVal.text || JSON.stringify(enVal)) : null,
      });
    }
  }

  // Production gaps first
  items.sort((a, b) => (a.intentional ? 1 : 0) - (b.intentional ? 1 : 0));
  return items;
}

/**
 * buildContentIntegrityNotices — maps lib/check-key-alignment.js's orphan-page,
 * wip/-collision, and duplicate-wip/-intent findings into the standard notice
 * item shape ({title, description, priority, context}) every other category
 * already uses, so renderHealthPanel() needs no special case for this one.
 * All informational (see check-key-alignment.js's header for why nothing here
 * blocks a build) — priority reflects urgency of attention, not build-blocking.
 */
function buildContentIntegrityNotices(orphanPages, wipCollisions, wipDuplicateIntents) {
  const items = [];

  for (const slug of (orphanPages || [])) {
    items.push({
      title:       `Orphan page: ${slug}`,
      description: `pages/${slug}.html exists with no matching data/nodes.json entry.`,
      priority:    'low',
      context:     'orphan-page',
    });
  }

  for (const { file, slug } of (wipCollisions || [])) {
    items.push({
      title:       `wip/ collision: ${slug}`,
      description: `${file} declares _meta.slug "${slug}", which already exists as a real page. Placing it there would conflict with existing content.`,
      priority:    'high',
      context:     file,
    });
  }

  for (const { slug, files } of (wipDuplicateIntents || [])) {
    items.push({
      title:       `Duplicate wip/ intent: ${slug}`,
      description: `Multiple wip/ files declare the same intended slug: ${files.join(', ')}.`,
      priority:    'medium',
      context:     'wip-duplicate-intent',
    });
  }

  return items;
}

/**
 * buildStatusRollup — assembles the full status.json object from notice arrays.
 * meta.lattice, if provided (see buildLatticeCoverage), is passed through to _meta.
 */
function buildStatusRollup(notices, meta) {
  const { translation, techDebt, enhancements, assumptions, openDiscussions, contentIntegrity } = notices;

  const genuinePending = (translation || []).filter(t => !t.intentional);

  return {
    _meta: {
      generated:   meta.generated  || new Date().toISOString(),
      commit:      meta.commit     || 'unknown',
      totalOpen:   countOpen({ translation: genuinePending, techDebt, enhancements, assumptions, openDiscussions, contentIntegrity }),
      lattice:     meta.lattice    || null,
    },
    notices: {
      translation: {
        label:         'Needs Translation',
        autoGenerated: true,
        count:         genuinePending.length,
        items:         genuinePending,
        fixtures:      (translation || []).filter(t => t.intentional),
      },
      techDebt: {
        label:         'Tech Debt',
        autoGenerated: false,
        count:         (techDebt || []).length,
        items:         techDebt || [],
      },
      enhancements: {
        label:         'Planned Enhancements',
        autoGenerated: false,
        count:         (enhancements || []).length,
        items:         enhancements || [],
      },
      assumptions: {
        label:         'Unverified Assumptions',
        autoGenerated: false,
        count:         (assumptions || []).length,
        items:         assumptions || [],
      },
      openDiscussions: {
        label:         'Open Discussions',
        autoGenerated: false,
        count:         (openDiscussions || []).length,
        items:         openDiscussions || [],
      },
      contentIntegrity: {
        label:         'Content Integrity',
        autoGenerated: true,
        count:         (contentIntegrity || []).length,
        items:         contentIntegrity || [],
      },
    },
  };
}

/**
 * countOpen — total open items across all categories.
 * Translation fixtures are excluded (intentional, not debt).
 */
function countOpen(notices) {
  return (
    (notices.translation      || []).filter(t => !t.intentional).length +
    (notices.techDebt         || []).length +
    (notices.enhancements     || []).length +
    (notices.assumptions      || []).length +
    (notices.openDiscussions  || []).length +
    (notices.contentIntegrity || []).length
  );
}

/**
 * buildLatticeCoverage — mapped vs. total eligible .js files in lib/+widgets/.
 * "Eligible" mirrors lib/build-lattice-headers.js's isEligibleNode: ends in
 * .js, not sw.js, not under dist/. latticeMap is the parsed lattice-map.json;
 * libWidgetsJsFiles is every .js file path (repo-relative, e.g. 'lib/foo.js')
 * found under lib/ and widgets/.
 */
function buildLatticeCoverage(latticeMap, libWidgetsJsFiles) {
  const isEligible = (file) => file.endsWith('.js') && file !== 'sw.js' && !file.startsWith('dist/');
  const mappedNodes = Object.keys((latticeMap && latticeMap.nodes) || {}).filter(isEligible);
  const totalFiles  = (libWidgetsJsFiles || []).filter(isEligible);

  return {
    mappedNodes: mappedNodes.length,
    totalFiles:  totalFiles.length,
    coveragePct: totalFiles.length ? Math.round((mappedNodes.length / totalFiles.length) * 100) : 0,
  };
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const manifest     = JSON.parse(fs.readFileSync(path.join(COMPILED, 'manifest.json'), 'utf8'));
  const flatEn       = JSON.parse(fs.readFileSync(path.join(COMPILED, 'strings.en.json'), 'utf8'));
  const index        = JSON.parse(fs.readFileSync(INDEX_IN, 'utf8'));
  const supportedLangs = index.supportedLangs || ['en', 'ja'];

  // Demo scopes: walk data/strings/compiled/scopes/demo/ recursively,
  // converting path separators to dots to get the scope name.
  // e.g. pages/specimen-partial-translation.en.json → pages.specimen-partial-translation
  const demoScopesDir = path.join(COMPILED, 'scopes', 'demo');
  const demoScopes    = [];
  (function walk(dir, prefix) {
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (fs.statSync(full).isDirectory()) {
        walk(full, prefix ? `${prefix}.${entry}` : entry);
      } else if (entry.endsWith('.en.json')) {
        demoScopes.push((prefix ? `${prefix}.` : '') + entry.replace(/\.en\.json$/, ''));
      }
    }
  }(demoScopesDir, ''));

  const techDebt        = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'tech-debt.json'),            'utf8')).items;
  const enhancements    = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'planned-enhancements.json'), 'utf8')).items;
  const assumptions     = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'assumptions.json'),          'utf8')).items;
  const openDiscussions = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'open-discussions.json'),     'utf8')).items;

  const { execSync } = require('child_process');
  let commit = 'unknown';
  try { commit = execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim(); } catch (_) {}

  // Lattice coverage: docs/lattice-map.json nodes vs. every .js file under lib/+widgets/.
  const latticeMap = JSON.parse(fs.readFileSync(path.join(ROOT, 'docs', 'lattice-map.json'), 'utf8'));
  const libWidgetsJsFiles = [];
  for (const dir of ['lib', 'widgets']) {
    for (const entry of fs.readdirSync(path.join(ROOT, dir))) {
      if (entry.endsWith('.js')) libWidgetsJsFiles.push(`${dir}/${entry}`);
    }
  }
  const lattice = buildLatticeCoverage(latticeMap, libWidgetsJsFiles);

  const { checkKeyAlignment } = require('./check-key-alignment');
  const alignment      = checkKeyAlignment();
  const contentIntegrity = buildContentIntegrityNotices(
    alignment.pages.orphans,
    alignment.wip.collisions,
    alignment.wip.duplicateIntents
  );

  const translation = buildTranslationNotices(manifest, flatEn, supportedLangs, demoScopes);
  const rollup      = buildStatusRollup(
    { translation, techDebt, enhancements, assumptions, openDiscussions, contentIntegrity },
    { commit, lattice }
  );

  fs.writeFileSync(STATUS_OUT, JSON.stringify(rollup, null, 2));

  const { notices: n } = rollup;
  console.log('[build-status] Done.');
  console.log(`  translation      : ${n.translation.count} pending, ${n.translation.fixtures.length} intentional fixtures`);
  console.log(`  tech debt        : ${n.techDebt.count} items`);
  console.log(`  enhancements     : ${n.enhancements.count} items`);
  console.log(`  assumptions      : ${n.assumptions.count} items`);
  console.log(`  open discussions : ${n.openDiscussions.count} items`);
  console.log(`  content integrity: ${n.contentIntegrity.count} items`);
  console.log(`  lattice coverage : ${lattice.mappedNodes}/${lattice.totalFiles} (${lattice.coveragePct}%)`);
  console.log(`  total open       : ${rollup._meta.totalOpen}`);
  console.log(`  output           : ${STATUS_OUT}`);
}

module.exports = { buildTranslationNotices, buildStatusRollup, countOpen, buildLatticeCoverage, buildContentIntegrityNotices };

// [VXG RealForever]
