#!/usr/bin/env node
/**
 * VEXTREME — lib/build-sitemap.js
 *
 * Generates sitemap.xml at repo root — lists all live pages for crawlers.
 * Only includes pages that actually exist in pages/ (ported nodes).
 * Unported nodes are excluded — no 404s in the sitemap.
 *
 * Run manually:   node lib/build-sitemap.js
 * Auto-run via:   .github/workflows/build-index.yml
 *
 * lastmod (Session 027 fix): previously every URL was stamped with the build
 * date regardless of whether that page's content actually changed — since
 * build-index.yml's trigger paths cover nearly any change, this meant
 * "every page changed today" on almost every build, which defeats the point
 * of lastmod (telling crawlers what's actually worth re-crawling). Now
 * computed per file from real git history (git log -1 --format=%aI, the
 * commit-author-date of that file's last change), falling back to today
 * only when git can't resolve one (new uncommitted file, shallow clone).
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : generates sitemap.xml — lists only pages that actually exist, so crawlers never hit a 404
 *   reads     : data/nodes.json
 *               pages∕*.html (existence check only, per slug)
 *               git log (per-file last-change date, via subprocess)
 *   writes    : sitemap.xml
 *   loaded-by : .github/workflows/build-index.yml
 *   tested-by : (none)
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     a new utility page added (non-node, not from nodes.json):
 *       - UTILITY_PAGES array in this file — otherwise it's silently excluded from the sitemap
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT      = path.join(__dirname, '..');
const PAGES_DIR = path.join(ROOT, 'pages');
const GH_BASE   = 'https://vgong24.github.io/Vextreme/pages';

const nodes = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'nodes.json'), 'utf8'));

// ── Pure computation ─────────────────────────────────────────────────────────

// dateOnlyFromGitLog — extracts a YYYY-MM-DD date from `git log -1
// --format=%aI` output (a full ISO-8601 timestamp with timezone offset), or
// null if the output is empty/unusable. Pure string parsing so it's testable
// without a real git subprocess.
function dateOnlyFromGitLog(gitLogOutput) {
  const trimmed = (gitLogOutput || '').trim();
  if (!trimmed) return null;
  const m = trimmed.match(/^(\d{4}-\d{2}-\d{2})/);
  return m ? m[1] : null;
}

// ── I/O — real per-file git history ──────────────────────────────────────────

const today = new Date().toISOString().split('T')[0];

// lastmodForFile — the real date this file last changed in git, or today as
// a fallback (new uncommitted file, or a shallow clone that can't resolve
// history for it). Never throws — a sitemap date is not worth failing a build over.
function lastmodForFile(absPath) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%aI', '--', absPath], { cwd: ROOT, encoding: 'utf8' });
    return dateOnlyFromGitLog(out) || today;
  } catch (e) {
    return today;
  }
}

// ── Collect live pages ────────────────────────────────────────────────────────

// Utility pages to include in sitemap (non-node pages)
const UTILITY_PAGES = ['archives', 'vextreme-demo', 'specimens', 'specimen-full-translation', 'specimen-partial-translation', 'specimen-smallest-miss'];

const urls = [];

// Ported content nodes (sorted by timeline id)
const portedNodes = nodes
  .filter(n => n.id !== null && fs.existsSync(path.join(PAGES_DIR, n.slug + '.html')))
  .sort((a, b) => a.id - b.id);

for (const node of portedNodes) {
  const pagePath = path.join(PAGES_DIR, node.slug + '.html');
  urls.push({ loc: `${GH_BASE}/${node.slug}.html`, lastmod: lastmodForFile(pagePath) });
}

// Utility pages
for (const slug of UTILITY_PAGES) {
  const pagePath = path.join(PAGES_DIR, slug + '.html');
  if (fs.existsSync(pagePath)) {
    urls.push({ loc: `${GH_BASE}/${slug}.html`, lastmod: lastmodForFile(pagePath) });
  }
}

// ── Generate XML ──────────────────────────────────────────────────────────────

const urlEntries = urls.map(({ loc, lastmod }) =>
  `  <url>\n    <loc>${loc}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`
).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>`;

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml);

console.log(`[build-sitemap] Done.`);
console.log(`  live pages : ${portedNodes.length}`);
console.log(`  output     : sitemap.xml`);

// [VXG RealForever]
