#!/usr/bin/env node
/**
 * VEXTREME — lib/build-roles.js
 *
 * Compiles data/council-kernel.json's roster into data/roles.json — a
 * traceable "roles and contributions" registry: each role's position within
 * the decision triangle, its real position (org-wide, not department-scoped —
 * see docs/architecture/14-council-model.md for why the Council and
 * data/departments.json are different axes), and which real backlog items
 * (data/status/*.json's optional `lens` field) actually invoked its judgment.
 *
 * Why this exists: Session 022's Council Lenses panel gave each role a name
 * and a place to be looked up, but a role with no traceable link to a real
 * decision is exactly the "randomly placed" gap this closes — every role here
 * is either linked to at least one real contribution or explicitly shown with
 * zero, not silently omitted.
 *
 * Pure functions exported for testing:
 *   classifyDecisionRole(roleId, kernel) → 'decider' | 'gate' | 'surface' | 'perceiver'
 *   collectContributions(roleId, statusItemsBySource) → [{ id, title, source, priority }]
 *   buildRolesManifest(kernel, statusItemsBySource) → { council, decisionTriangle, channels, roles }
 *
 * Run manually:   node lib/build-roles.js
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : compiles data/council-kernel.json's roster + data/status∕*.json's lens fields into data/roles.json — the traceable roles/contributions registry
 *   reads     : data/council-kernel.json
 *               data/status/open-discussions.json
 *               data/status/tech-debt.json
 *               data/status/planned-enhancements.json
 *   writes    : data/roles.json
 *   loaded-by : manual run: node lib/build-roles.js
 *               .github/workflows/build-index.yml (CI)
 *               pages/roles-index.html (live fetch, browser — via lib/build-roles-page.js)
 *               tests/20-roles.test.js
 *   tested-by : tests/20-roles.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     an item gets (or loses) a lens field in data/status∕*.json:
 *       - no action needed — this script picks it up automatically on its next run
 *     data/council-kernel.json roster/decisionTriangle/connectionArchitecture schema changed:
 *       - buildRolesManifest() / classifyDecisionRole() in this file
 *       - lib/build-roles-page.js renderRoles()/renderChannels() (reads the same fields back out)
 *       - tests/20-roles.test.js
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT         = path.join(__dirname, '..');
const KERNEL_PATH   = path.join(ROOT, 'data', 'council-kernel.json');
const STATUS_DIR    = path.join(ROOT, 'data', 'status');
const OUT_JSON      = path.join(ROOT, 'data', 'roles.json');

const STATUS_SOURCES = [
  { file: 'open-discussions.json',    key: 'openDiscussions' },
  { file: 'tech-debt.json',           key: 'techDebt' },
  { file: 'planned-enhancements.json',key: 'plannedEnhancements' },
];

// ── Pure computation ──────────────────────────────────────────────────────────

// classifyDecisionRole — where a role sits relative to org-blueprint.html's
// decision triangle: the three deciders who loop until satisfied, the three
// gates that verify the decision's output, the surface that speaks it, or a
// perceiver/calibration role that feeds the triangle but doesn't sit on it.
function classifyDecisionRole(roleId, kernel) {
  const triangle = kernel.decisionTriangle || {};
  if ((triangle.deciders || []).includes(roleId)) return 'decider';
  if (Object.keys(triangle.gates || {}).includes(roleId)) return 'gate';
  if (roleId === 'surface') return 'surface';
  return 'perceiver';
}

// collectContributions — every real item across the three status sources
// whose `lens` field names this role. Returned sorted by id for stable output.
function collectContributions(roleId, statusItemsBySource) {
  const contributions = [];
  for (const { key, items } of statusItemsBySource) {
    for (const item of items) {
      if (item.lens === roleId) {
        contributions.push({ id: item.id, title: item.title, source: key, priority: item.priority || 'low' });
      }
    }
  }
  contributions.sort((a, b) => a.id.localeCompare(b.id));
  return contributions;
}

// buildRolesManifest — the full compiled registry. `position` is deliberately
// the same string for every role today ("org-wide — The Council"): only one
// council exists in this repo (see docs/architecture/14-council-model.md),
// not one per department, so claiming a per-department position would be
// overclaiming a structure that doesn't exist yet. channels pass through
// connectionArchitecture unmodified plus one added field, `manifestation`,
// naming what (if anything) currently instantiates that channel for real.
function buildRolesManifest(kernel, statusItemsBySource) {
  const roles = (kernel.roles || []).map(role => ({
    id:            role.id,
    holds:         role.holds,
    failsAs:       role.failsAs,
    caughtBy:      role.caughtBy || [],
    decisionRole:  classifyDecisionRole(role.id, kernel),
    position:      'org-wide — The Council (pages/org-blueprint.html); not department-scoped, see docs/architecture/14-council-model.md',
    contributions: collectContributions(role.id, statusItemsBySource),
  }));

  const conn = kernel.connectionArchitecture || {};
  const channelManifestations = {
    plenary:            "data/status.json's panels on pages/ecosystem-hub.html — every notice category co-present at one origin, cross-witnessed by anyone who opens the page.",
    vertical:           'Session continuity (docs/continuity/INDEX.md + batch files) — root-to-head flow between Victor and the current AI instance across sessions.',
    intraCouncilRelay:  "The Scanner pass documented in docs/architecture/14-council-model.md's \"First attempt\" section — run once, by hand, not yet an automated relay.",
    crossCouncilBridge: 'Not yet real — only one council exists in this repo today; pages/bridge-council*.html describe a genuinely different multi-council pattern, not this one (see docs/architecture/14-council-model.md).',
  };

  const channels = {};
  for (const [name, description] of Object.entries(conn.channels || {})) {
    channels[name] = { description, manifestation: channelManifestations[name] || 'Not yet mapped to a real mechanism.' };
  }

  return {
    council: {
      name: 'The Council',
      sourceDoc: kernel.sourceDoc,
      scope: "One mind holding multiple internal faculties, org-wide — a different axis from data/departments.json's production-domain grouping. See docs/architecture/14-council-model.md.",
    },
    decisionTriangle: kernel.decisionTriangle || null,
    channels,
    roles,
  };
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const kernel = JSON.parse(fs.readFileSync(KERNEL_PATH, 'utf8'));

  const statusItemsBySource = STATUS_SOURCES.map(({ file, key }) => ({
    key,
    items: JSON.parse(fs.readFileSync(path.join(STATUS_DIR, file), 'utf8')).items || [],
  }));

  const manifest = buildRolesManifest(kernel, statusItemsBySource);
  fs.writeFileSync(OUT_JSON, JSON.stringify(manifest, null, 2));

  const totalContributions = manifest.roles.reduce((n, r) => n + r.contributions.length, 0);
  console.log(`[build-roles] Compiled ${manifest.roles.length} role(s), ${totalContributions} traced contribution(s) into data/roles.json`);
}

module.exports = { classifyDecisionRole, collectContributions, buildRolesManifest };

// [VXG RealForever]
