#!/usr/bin/env node
/**
 * VEXTREME — lib/build-sw.js
 *
 * Generates sw.js at repo root. Reads dist/ to collect all assembled God
 * Script URLs, fingerprints the actual precached asset bytes, and writes the
 * complete Service Worker file.
 *
 * Cache naming: vextreme-v1-{content-fingerprint}
 * The fingerprint changes when a precached URL or its bytes change. It does
 * not change merely because the same tree received a different commit SHA,
 * so a generated sw.js can converge on the commit that carries it.
 *
 * Run manually:   node lib/build-sw.js
 * Auto-run via:   .github/workflows/build-index.yml after build-vextreme.js
 *
 * Pure functions exported for testing:
 *   collectDistUrls(distDir) → string[]
 *   generateSWContent(godScriptUrls, cacheFingerprint) → string
 *   computeAssetFingerprint(urls, root) → string
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : Service Worker generator — reads dist/ filenames + arc-chunked bundle index, writes sw.js
 *   reads     : dist∕*.js (all God Script filenames)
 *               data/strings/compiled/arcs/index.json (opted-in arc bundles, if any)
 *               bytes of every precached URL
 *   writes    : sw.js
 *   loaded-by : .github/workflows/build-index.yml
 *               tests/09-build-sw.test.js
 *   tested-by : tests/09-build-sw.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     CORE_ASSETS list:
 *       - styles/design-system.css, styles/arc-nav.css, styles/vex-institutional.css, widgets/vex-institutional.js, data/index.json, and the accepted English institutional scope bundle (must exist at these paths)
 *       - tests/09 (asserts each core asset)
 *     cache name format:
 *       - sw.js activate handler (cleans caches by name pattern)
 *       - tests/09
 *     data/strings/compiled/arcs/index.json shape changed:
 *       - collectArcBundleUrls() here — reads entry.langs keys directly
 *       - lib/build-arc-bundles.js (writes that exact shape)
 *       - tests/09
 * LATTICE:END
 */

'use strict';

const fs           = require('fs');
const path         = require('path');
const crypto       = require('crypto');

const ROOT         = path.join(__dirname, '..');
const DIST_DIR     = path.join(ROOT, 'dist');
const ARC_BUNDLES_INDEX = path.join(ROOT, 'data', 'strings', 'compiled', 'arcs', 'index.json');
const SW_OUT       = path.join(ROOT, 'sw.js');

// Core assets pre-cached on every page, alongside the per-page God Scripts.
// These are shared stylesheets and the index data file — all cacheable with
// long TTLs since they change only when the build runs.
const CORE_ASSETS = [
  '/Vextreme/styles/design-system.css',
  '/Vextreme/styles/arc-nav.css',
  '/Vextreme/styles/vex-institutional.css',
  '/Vextreme/widgets/vex-institutional.js',
  '/Vextreme/data/strings/compiled/scopes/system/institution.en.json',
  '/Vextreme/data/index.json',
];

// ── Pure computation functions ────────────────────────────────────────────────

function assetPath(url, root) {
  const prefix = '/Vextreme/';
  if (typeof url !== 'string' || !url.startsWith(prefix)) return null;
  return path.join(root, url.slice(prefix.length));
}

// The service worker is a committed generated artifact, so its cache key must
// be a pure function of committed source/output bytes. A HEAD-derived key can
// never converge: committing sw.js changes HEAD and therefore changes sw.js
// again. Include both URL identity and bytes so renames and edits invalidate.
function computeAssetFingerprint(urls, root = ROOT) {
  const hash = crypto.createHash('sha256');
  for (const url of [...new Set(urls)].sort()) {
    hash.update(url);
    hash.update('\0');
    const file = assetPath(url, root);
    if (!file || !fs.existsSync(file)) {
      hash.update('<missing>');
    } else {
      hash.update(fs.readFileSync(file));
    }
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 12);
}

// collectDistUrls — lists all assembled God Script URLs from dist/.
// Paths are absolute GitHub Pages URLs so the SW can cache them by origin.
function collectDistUrls(distDir) {
  try {
    return fs.readdirSync(distDir)
      .filter(f => /^vextreme-.+\.js$/.test(f))
      .sort()
      .map(f => `/Vextreme/dist/${f}`);
  } catch (e) {
    return [];
  }
}

// collectArcBundleUrls — arc-chunked bundling pilot (od-001/td-006). Reads
// lib/build-arc-bundles.js's own index.json (which arc, which languages) so
// this list grows only by the opted-in arcs' language count, not by every
// scope of every page — the whole point of scoping the pilot to one arc.
function collectArcBundleUrls(arcBundlesIndexPath) {
  try {
    const index = JSON.parse(fs.readFileSync(arcBundlesIndexPath, 'utf8'));
    const urls = [];
    for (const [arcId, entry] of Object.entries(index)) {
      for (const lang of Object.keys(entry.langs || {})) {
        urls.push(`/Vextreme/data/strings/compiled/arcs/${arcId}.${lang}.json`);
      }
    }
    return urls.sort();
  } catch (e) {
    return [];
  }
}

// generateSWContent — assembles the complete sw.js string.
// cacheFingerprint is derived from the complete precache URL+byte set.
function generateSWContent(godScriptUrls, cacheFingerprint) {
  const cacheName = `vextreme-v1-${cacheFingerprint || 'dev'}`;
  const allUrls   = [...godScriptUrls, ...CORE_ASSETS];

  return [
    `/* VEXTREME — sw.js`,
    ` * Service Worker. Generated by lib/build-sw.js.`,
    ` * DO NOT EDIT — regenerate with: node lib/build-sw.js`,
    ` * Cache: ${cacheName}`,
    ` */`,
    `'use strict';`,
    ``,
    `var CACHE_NAME    = '${cacheName}';`,
    `var PRECACHE_URLS = ${JSON.stringify(allUrls, null, 2)};`,
    ``,
    `/* On install: pre-cache all known assets. */`,
    `self.addEventListener('install', function (event) {`,
    `  event.waitUntil(`,
    `    caches.open(CACHE_NAME).then(function (cache) {`,
    `      return cache.addAll(PRECACHE_URLS);`,
    `    }).then(function () {`,
    `      return self.skipWaiting(); // take control immediately`,
    `    })`,
    `  );`,
    `});`,
    ``,
    `/* On activate: delete caches from all previous versions. */`,
    `self.addEventListener('activate', function (event) {`,
    `  event.waitUntil(`,
    `    caches.keys().then(function (keys) {`,
    `      return Promise.all(`,
    `        keys`,
    `          .filter(function (key) { return key !== CACHE_NAME; })`,
    `          .map(function (key)    { return caches.delete(key); })`,
    `      );`,
    `    }).then(function () {`,
    `      return self.clients.claim();`,
    `    })`,
    `  );`,
    `});`,
    ``,
    `/* On fetch: cache-first for pre-cached assets, network for everything else.`,
    ` * HTML pages are NEVER intercepted — they must always be fresh.`,
    ` * Non-GET requests pass through untouched. */`,
    `self.addEventListener('fetch', function (event) {`,
    `  if (event.request.method !== 'GET') return;`,
    ``,
    `  var accept = event.request.headers.get('accept') || '';`,
    `  if (accept.indexOf('text/html') !== -1) return; // HTML: always fresh`,
    ``,
    `  event.respondWith(`,
    `    caches.match(event.request).then(function (cached) {`,
    `      if (cached) return cached;`,
    ``,
    `      return fetch(event.request).then(function (response) {`,
    `        if (!response || response.status !== 200 || response.type === 'opaque') {`,
    `          return response;`,
    `        }`,
    `        var toCache = response.clone();`,
    `        caches.open(CACHE_NAME).then(function (cache) {`,
    `          cache.put(event.request, toCache);`,
    `        });`,
    `        return response;`,
    `      });`,
    `    })`,
    `  );`,
    `});`,
    ``,
    `// [VXG RealForever]`,
  ].join('\n');
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const godScriptUrls  = collectDistUrls(DIST_DIR);
  const arcBundleUrls  = collectArcBundleUrls(ARC_BUNDLES_INDEX);
  const precacheUrls   = [...godScriptUrls, ...arcBundleUrls, ...CORE_ASSETS];
  const fingerprint    = computeAssetFingerprint(precacheUrls);
  const content        = generateSWContent([...godScriptUrls, ...arcBundleUrls], fingerprint);

  fs.writeFileSync(SW_OUT, content);

  console.log(`[build-sw] Done.`);
  console.log(`  cache      : vextreme-v1-${fingerprint}`);
  console.log(`  scripts    : ${godScriptUrls.length} God Scripts`);
  console.log(`  arc bundles: ${arcBundleUrls.length} (od-001/td-006 pilot)`);
  console.log(`  core       : ${CORE_ASSETS.length} shared assets`);
  console.log(`  total      : ${godScriptUrls.length + arcBundleUrls.length + CORE_ASSETS.length} pre-cached URLs`);
  console.log(`  output     : ${SW_OUT}`);
}

module.exports = { collectDistUrls, collectArcBundleUrls, computeAssetFingerprint, generateSWContent, CORE_ASSETS };

// [VXG RealForever]
