#!/usr/bin/env node
/**
 * VEXTREME — lib/build-index.js
 *
 * Reads data/nodes.json + data/arcs-v2.json → writes data/index.json
 *
 * Run manually:   node lib/build-index.js
 * Auto-run via:   .github/workflows/build-index.yml on push to main
 *
 * Output (data/index.json) is the pre-built index consumed by the browser.
 * Never edit index.json directly — edit the source files and rebuild.
 *
 * Pure computation functions are exported for testing:
 *   buildViewmodel(slug, viewmodels) → viewmodel
 *   buildSlugMap(nodes, arcsDef, viewmodels) → slugMap
 *   buildArcMap(nodes, arcsDef, slugMap) → arcMap
 *   buildArcMeta(arcsDef) → arcMeta
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : content pipeline assembler — reads source data, writes the single pre-built index everything reads from
 *   reads     : data/nodes.json
 *               data/arcs-v2.json
 *               data/viewmodels.json
 *               data/departments.json
 *               pages∕*.html (via lib/auto-discover-nodes.js, for any slug with no nodes.json entry)
 *               lib/audit-pages.js (SKIP_PAGES, getPageSlugs)
 *               lib/auto-discover-nodes.js (discoverOrphanNodes, readPageFromDisk)
 *               lib/vex-config.js
 *   writes    : data/index.json
 *   loaded-by : lib/vextreme-index-v2.js (browser reads index.json via CDN)
 *               lib/build-vextreme.js (reads index.json for slugMap + supportedLangs)
 *               lib/check-key-alignment.js
 *               lib/audit-pages.js
 *               lib/build-ecosystem-hub.js (departmentMap/departmentMeta, live fetch)
 *               tests/01-content-pipeline.test.js
 *               tests/03-browser-nav.test.js
 *               tests/07-viewmodel.test.js
 *               tests/08-build-vextreme.test.js (via KEY-ALIGNMENT tests)
 *               tests/15-departments.test.js
 *               tests/16-auto-discover-nodes.test.js
 *   tested-by : tests/01-content-pipeline.test.js
 *               tests/03-browser-nav.test.js
 *               tests/07-viewmodel.test.js
 *               tests/15-departments.test.js
 *               tests/16-auto-discover-nodes.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     slugMap schema:
 *       - lib/vextreme-index-v2.js (buildArcNavData reads slugMap)
 *       - lib/build-vextreme.js (resolveAllSlugs reads slugMap)
 *       - tests/01, tests/03, tests/07, tests/08
 *     arcMap schema:
 *       - lib/vextreme-index-v2.js (buildArcNavData reads arcMap)
 *       - tests/01, tests/03
 *     arcMeta schema:
 *       - lib/vextreme-index-v2.js (renderArcRow reads arcMeta)
 *       - tests/01
 *     supportedLangs field:
 *       - lib/build-vextreme.js (passes into every God Script as window.VEX_SUPPORTED_LANGS)
 *       - tests/08
 *     viewmodel shape:
 *       - data/viewmodels.json
 *       - lib/build-vextreme.js (assembleGodScript uses viewmodel fields)
 *       - tests/07-viewmodel.test.js
 *     departmentMap / departmentMeta schema:
 *       - data/departments.json (registry — add a department or workType here first)
 *       - lib/build-ecosystem-hub.js (renderDepartments reads both, browser-side)
 *       - tests/15-departments.test.js
 *     findDuplicateSlugs / SLUG_DUPLICATE guard:
 *       - lib/logger-codes.js (SLUG_DUPLICATE entry, grouped under build-index.js)
 *       - tests/01-content-pipeline.test.js (SLUGS: tests)
 *       - docs/architecture/02-slug.md ('path is derived from slug' principle this guard protects)
 *     auto-discovery logic changed (discoverOrphanNodes' output shape or defaults):
 *       - lib/auto-discover-nodes.js (the shared implementation both this file and lib/build-archives.js call)
 *       - lib/build-archives.js (calls the same function independently — see pe-011, tracked to collapse this someday)
 *       - tests/16-auto-discover-nodes.test.js
 *       - tests/15-departments.test.js (its integration test replicates the allNodes computation)
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');
const { logger } = require('./logger');
const { CODES }  = require('./logger-codes');
const { Language, DEFAULT_CATEGORY, Feature } = require('./vex-config');
const { SKIP_PAGES, getPageSlugs } = require('./audit-pages');
const { discoverOrphanNodes, readPageFromDisk } = require('./auto-discover-nodes');

const ROOT           = path.join(__dirname, '..');
const NODES_IN       = path.join(ROOT, 'data', 'nodes.json');
const ARCS_IN        = path.join(ROOT, 'data', 'arcs-v2.json');
const VIEWMODELS_IN  = path.join(ROOT, 'data', 'viewmodels.json');
const DEPARTMENTS_IN = path.join(ROOT, 'data', 'departments.json');
const PAGES_DIR      = path.join(ROOT, 'pages');
const INDEX_OUT      = path.join(ROOT, 'data', 'index.json');

// ── Date parsing ─────────────────────────────────────────────────────────────

function parseDate(str) {
  if (!str) return null;
  // "Feb 7–10, 2026" → use start date "Feb 7, 2026"
  const fixed = str.replace(/^(\w+)\s+(\d+)[–\-]\d+,\s+(\d{4})$/, '$1 $2, $3');
  const d = new Date(fixed);
  return isNaN(d.getTime()) ? null : d;
}

function toDateISO(str) {
  if (!str) return null;
  const fixed = str.replace(/^(\w+)\s+(\d+)[–\-]\d+,\s+(\d{4})$/, '$1 $2, $3');
  const d = new Date(fixed);
  if (isNaN(d.getTime())) return null;
  return d.toISOString().split('T')[0]; // "YYYY-MM-DD"
}

// ── Pure computation functions ────────────────────────────────────────────────

// buildViewmodel — derives the per-page viewmodel for a slug.
// Merges the slug's override from data/viewmodels.json with safe defaults.
// The viewmodel is the contract between the build pipeline and the God Script
// assembler: it tells the assembler which category, template, scopes, and
// features to inline for this page.
function buildViewmodel(slug, viewmodels) {
  const override = (viewmodels || {})[slug] || {};
  return {
    category: override.category || DEFAULT_CATEGORY,
    template: override.template || 'page',
    scopes:   override.scopes   || [`pages.${slug}`],
    features: override.features || [Feature.LANG, Feature.SPIRAL_FAB],
  };
}

// buildSlugMap — O(1) lookup table from slug → node with derived fields.
// arcKeys re-sorted by arc priority so the browser renders in correct order.
// viewmodels is the parsed data/viewmodels.json override map (optional).
function buildSlugMap(nodes, arcsDef, viewmodels) {
  const slugMap = {};
  for (const node of nodes) {
    const sortedArcKeys = node.arcKeys.slice().sort((a, b) => {
      const pa = arcsDef[a]?.priority ?? 50;
      const pb = arcsDef[b]?.priority ?? 50;
      return pa - pb;
    });
    slugMap[node.slug] = {
      ...node,
      arcKeys:   sortedArcKeys,
      dateISO:   toDateISO(node.date),
      viewmodel: buildViewmodel(node.slug, viewmodels),
    };
  }
  return slugMap;
}

// buildArcMap — resolves each arc's sections into ordered slug lists.
// Supports 'explicit' (manually ordered) and 'chronological' (date-sorted) sections.
function buildArcMap(nodes, arcsDef, slugMap) {
  const arcMap = {};

  for (const [arcName, arcDef] of Object.entries(arcsDef)) {
    if (arcName.startsWith('_')) continue;

    const resolvedSections = [];

    for (const section of arcDef.sections) {
      let orderedSlugs = [];

      if (section.order === 'explicit') {
        orderedSlugs = (section.slugs || []).filter(slug => {
          if (!slugMap[slug]) {
            logger.warn({ code: CODES.SLUG_NOT_IN_NODES, message: `slug not in nodes.json — skipped`, arc: arcName, section: section.label, slug });
            return false;
          }
          return true;
        });

      } else {
        // chronological — filter nodes whose arcKeys include this arc
        let items = nodes.filter(n => n.arcKeys.includes(arcName));

        // Narrow by dateRange if defined (required for full_timeline sections)
        if (section.dateRange) {
          const from = new Date(section.dateRange.from);
          const to   = new Date(section.dateRange.to);
          to.setHours(23, 59, 59, 999);
          items = items.filter(n => {
            const d = parseDate(n.date);
            return d !== null && d >= from && d <= to;
          });
        }

        items.sort((a, b) => {
          const da = parseDate(a.date);
          const db = parseDate(b.date);
          if (da === null && db === null) return 0;
          if (da === null) return 1;
          if (db === null) return -1;
          return da - db;
        });

        orderedSlugs = items.map(n => n.slug);
      }

      if (orderedSlugs.length > 0) {
        resolvedSections.push({ label: section.label, slugs: orderedSlugs });
      }
    }

    arcMap[arcName] = resolvedSections;
  }

  return arcMap;
}

// buildSupportedLangs — scans compiled strings directory for available bundles.
// Automatic: adding a new language to the strings pipeline makes it appear here.
function buildSupportedLangs() {
  const compiledDir = path.join(ROOT, 'data', 'strings', 'compiled');
  try {
    return fs.readdirSync(compiledDir)
      .filter(f => /^strings\.[a-z]{2,}\.json$/.test(f))
      .map(f => f.replace(/^strings\./, '').replace(/\.json$/, ''))
      .sort();
  } catch (e) {
    return [Language.EN];
  }
}

// buildArcMeta — extracts display metadata from arc definitions.
// Stored in index.json so the browser has no hard-coded arc tables.
function buildArcMeta(arcsDef) {
  const arcMeta = {};
  for (const [arcName, arcDef] of Object.entries(arcsDef)) {
    if (arcName.startsWith('_')) continue;
    arcMeta[arcName] = {
      title:      arcDef.parent?.title  ?? arcName,
      url:        arcDef.parent?.url    ?? '#',
      renderMode: arcDef.renderMode     ?? 'dots'
    };
  }
  return arcMeta;
}

// findDuplicateSlugs — BLOCK-severity guard: slug is the system's only identifier
// (docs/architecture/02-slug.md), so two nodes sharing a slug isn't a warning-level
// drift the way a stale index.json is — it's the map-based lookup (department →
// workType → slug → pages/{slug}.html) silently pointing at the wrong file, or
// buildSlugMap silently overwriting one node with another. Returns an array of
// { slug, count } for every slug that appears more than once; empty means clean.
function findDuplicateSlugs(nodes) {
  const counts = {};
  for (const node of nodes) {
    counts[node.slug] = (counts[node.slug] || 0) + 1;
  }
  return Object.entries(counts)
    .filter(([, count]) => count > 1)
    .map(([slug, count]) => ({ slug, count }));
}

// buildDepartmentMap — groups nodes by production-domain department + workType,
// a different axis than arcMap (reader-facing narrative grouping). A node with no
// department/workType field falls back to whichever department is marked default:true
// (and that department's 'default' workType). Each entry carries `ported` — whether
// pages/{slug}.html exists — the same ported-vs-not signal build-archives.js already
// computes per-arc, surfaced here per-department instead.
function buildDepartmentMap(nodes, departmentsDef) {
  const defaultDept = Object.keys(departmentsDef || {})
    .filter(id => !id.startsWith('_'))
    .find(id => departmentsDef[id].default) || 'rd';

  const map = {};
  for (const node of nodes) {
    const dept     = node.department || defaultDept;
    const workType = node.workType   || 'default';

    if (!map[dept]) map[dept] = {};
    if (!map[dept][workType]) map[dept][workType] = [];

    map[dept][workType].push({
      slug:   node.slug,
      title:  node.title,
      ported: fs.existsSync(path.join(PAGES_DIR, node.slug + '.html')),
    });
  }
  return map;
}

// buildDepartmentMeta — display metadata per department/workType, mirroring buildArcMeta.
// Stored in index.json so the ecosystem hub has no hard-coded department tables.
function buildDepartmentMeta(departmentsDef) {
  const meta = {};
  for (const [id, def] of Object.entries(departmentsDef || {})) {
    if (id.startsWith('_')) continue;
    const workTypes = {};
    for (const [wid, w] of Object.entries(def.workTypes || {})) {
      workTypes[wid] = { label: w.label || wid };
    }
    meta[id] = {
      label:     def.label || id,
      default:   !!def.default,
      workTypes,
    };
  }
  return meta;
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const nodes        = JSON.parse(fs.readFileSync(NODES_IN,  'utf8'));
  const arcsDef      = JSON.parse(fs.readFileSync(ARCS_IN,   'utf8'));
  const viewmodels   = fs.existsSync(VIEWMODELS_IN)
    ? JSON.parse(fs.readFileSync(VIEWMODELS_IN, 'utf8'))
    : {};
  const departmentsDef = fs.existsSync(DEPARTMENTS_IN)
    ? JSON.parse(fs.readFileSync(DEPARTMENTS_IN, 'utf8'))
    : {};

  const dupes = findDuplicateSlugs(nodes);
  if (dupes.length) {
    for (const { slug, count } of dupes) {
      logger.error({ code: CODES.SLUG_DUPLICATE, message: `slug appears ${count} times in data/nodes.json — slug must be globally unique`, slug, count });
    }
    console.error(`[build-index] BLOCKED — ${dupes.length} duplicate slug(s) found. Fix data/nodes.json before rebuilding.`);
    process.exit(1);
  }

  // Auto-discovery: a pages/*.html file with no nodes.json entry gets a
  // synthetic node (title scraped from <title>, department/workType from
  // <meta> tags or the registry default) so it's visible in departmentMap
  // and archives.html without anyone hand-editing nodes.json first. Never
  // written back to nodes.json — see lib/auto-discover-nodes.js's header.
  const nodeSlugsForDiscovery = nodes.map(n => n.slug);
  const viewmodelSlugs = Object.keys(viewmodels).filter(k => !k.startsWith('_'));
  const discovered = discoverOrphanNodes(getPageSlugs(), nodeSlugsForDiscovery, SKIP_PAGES, viewmodelSlugs, readPageFromDisk, departmentsDef);
  const allNodes = nodes.concat(discovered);

  const slugMap        = buildSlugMap(allNodes, arcsDef, viewmodels);
  const arcMap         = buildArcMap(allNodes, arcsDef, slugMap);
  const arcMeta        = buildArcMeta(arcsDef);
  const supportedLangs = buildSupportedLangs();
  const departmentMap  = buildDepartmentMap(allNodes, departmentsDef);
  const departmentMeta = buildDepartmentMeta(departmentsDef);

  const index = {
    builtAt:            new Date().toISOString(),
    nodeCount:          allNodes.length,
    curatedNodeCount:   nodes.length,
    autoDiscoveredCount: discovered.length,
    arcCount:     Object.keys(arcMap).length,
    supportedLangs,
    slugMap,
    arcMap,
    arcMeta,
    departmentMap,
    departmentMeta
  };

  fs.writeFileSync(INDEX_OUT, JSON.stringify(index, null, 2));

  console.log(`[build-index] Done.`);
  console.log(`  nodes       : ${index.nodeCount} (${index.curatedNodeCount} curated, ${index.autoDiscoveredCount} auto-discovered)`);
  console.log(`  arcs        : ${index.arcCount}`);
  console.log(`  departments : ${Object.keys(departmentMap).length}`);
  console.log(`  output      : ${INDEX_OUT}`);
}

module.exports = { buildViewmodel, buildSlugMap, buildArcMap, buildArcMeta, buildSupportedLangs, buildDepartmentMap, buildDepartmentMeta, findDuplicateSlugs, parseDate, toDateISO };

// [VXG RealForever]
