#!/usr/bin/env node
/**
 * VEXTREME — lib/build-lessons.js
 *
 * Assembles data/lessons.json from config/lessons/*.json — the read-side
 * manifest that lets pages/ecosystem-hub.html show the lesson archive without
 * fetching every individual lesson file itself.
 *
 * Why this exists: config/lessons/*.json has been the write-side home for
 * distilled architectural/process lessons since Session 010 (see
 * docs/architecture/08-continuity.md's "external collaboration documents"
 * table), but nothing compiled those files into anything the Ecosystem Hub
 * — the system's one dashboard for "what does this repo currently know" —
 * could read. A lesson wasn't invisible (`git log --grep`, grepping the
 * directory, or reading pages/specimen-architectural-wisdoms.html's
 * hand-authored decision cards all surfaced it), but it also wasn't
 * connected to the one page built to answer "what's the current state of
 * this system" without a targeted search. This mirrors the exact shape
 * lib/auto-discover-nodes.js solved for pages/: written content existing
 * on disk with no path into the generated read side that's supposed to
 * make it discoverable.
 *
 * Two lesson-file schema generations exist (both handled here):
 *   - newer: { sessions: [...] }               (Session 022+)
 *   - older: { pr: "#N", session: "0NN" }       (Session 010-011)
 * Both normalize to a single `sessions` array in the output; a lesson
 * with neither field just gets an empty array rather than failing the build.
 *
 * Pure functions exported for testing:
 *   normalizeLessonSessions(lesson) → string[]
 *   buildLessonsManifest(lessonFiles) → { count, items: [...] }
 *
 * Run manually:   node lib/build-lessons.js
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : compiles config/lessons∕*.json into data/lessons.json — the read-side manifest the Ecosystem Hub fetches
 *   reads     : config/lessons∕*.json (every lesson file, both schema generations)
 *   writes    : data/lessons.json
 *   loaded-by : manual run: node lib/build-lessons.js
 *               .github/workflows/build-index.yml (CI, Session 022)
 *               pages/ecosystem-hub.html (live fetch of the compiled output)
 *               tests/17-build-lessons.test.js
 *   tested-by : tests/17-build-lessons.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     a new lesson file added to config/lessons/:
 *       - no action needed — this script picks up every *.json file in the directory automatically on its next run (manual or CI)
 *     lesson file schema changed (new required field, field renamed):
 *       - buildLessonsManifest() in this file (the field mapping)
 *       - lib/build-ecosystem-hub.js renderLessons() (reads title/problem/lesson/impact/sessions/visual/relatedPRs/resolvedByPR)
 *       - tests/17-build-lessons.test.js
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT        = path.join(__dirname, '..');
const LESSONS_DIR = path.join(ROOT, 'config', 'lessons');
const OUT_JSON     = path.join(ROOT, 'data', 'lessons.json');

// ── Pure computation ──────────────────────────────────────────────────────────

// normalizeLessonSessions — collapses both schema generations (sessions: [...]
// vs. session: "0NN" / pr: "#N") into one sessions array so the render side
// never has to branch on which generation a given lesson file used.
function normalizeLessonSessions(lesson) {
  if (Array.isArray(lesson.sessions)) return lesson.sessions;
  if (lesson.session) return [lesson.session];
  return [];
}

// buildLessonsManifest — takes [{ filename, content }] (content already
// JSON.parsed), returns the compiled manifest. Sorted by id for stable output
// (avoids noisy diffs from directory-listing order).
function buildLessonsManifest(lessonFiles) {
  const items = lessonFiles.map(({ content }) => ({
    id:           content.id,
    title:        content.title,
    problem:      content.problem,
    lesson:       content.lesson,
    impact:       content.impact || '',
    sessions:     normalizeLessonSessions(content),
    visual:       content.visual || null,
    relatedPRs:   Array.isArray(content.relatedPRs) ? content.relatedPRs : [],
    resolvedByPR: content.resolvedByPR || null,
  }));

  items.sort((a, b) => a.id.localeCompare(b.id));

  return { count: items.length, items };
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const filenames = fs.readdirSync(LESSONS_DIR).filter(f => f.endsWith('.json'));
  const lessonFiles = filenames.map(filename => ({
    filename,
    content: JSON.parse(fs.readFileSync(path.join(LESSONS_DIR, filename), 'utf8')),
  }));

  const manifest = buildLessonsManifest(lessonFiles);
  fs.writeFileSync(OUT_JSON, JSON.stringify(manifest, null, 2));

  console.log(`[build-lessons] Compiled ${manifest.count} lesson(s) from config/lessons/ into data/lessons.json`);
}

module.exports = { normalizeLessonSessions, buildLessonsManifest };

// [VXG RealForever]
