#!/usr/bin/env node
/**
 * VEXTREME — lib/build-status.js
 *
 * Assembles data/status.json — the system health manifest.
 *
 * Six notice categories:
 *   translation     — auto-generated from strings/compiled/manifest.json
 *                     keys missing from any supported language (excluding demo
 *                     category pages where gaps are intentional fixtures)
 *   techDebt        — hand-authored in data/status/tech-debt.json (decided fix, not built)
 *   enhancements    — hand-authored in data/status/planned-enhancements.json (decided direction, not built)
 *   assumptions     — hand-authored in data/status/assumptions.json
 *   openDiscussions — hand-authored in data/status/open-discussions.json (a fork in the
 *                     road where the fork itself hasn't been chosen yet — see that file's
 *                     _comment for how this differs from techDebt/enhancements)
 *   contentIntegrity — auto-generated from lib/check-key-alignment.js: uncurated pages
 *                     (a pages/*.html file with no nodes.json entry — auto-discovered
 *                     and visible via lib/auto-discover-nodes.js, just not curated),
 *                     wip/ slug collisions (a wip/ file's declared _meta.slug already
 *                     exists as a real page), duplicate wip/ intents (two wip/ files
 *                     declaring the same slug), and wip/ html drafts (a raw wip/*.html
 *                     file with no destination yet — Session 022 continued: gives it a
 *                     visible entry the moment it's added, no manual mapping required).
 *                     Informational only — nothing here blocks a build; see
 *                     check-key-alignment.js's own header for why.
 *
 * Also computes lattice coverage (docs/lattice-map.json nodes vs. total eligible
 * .js files in lib/+widgets/) into _meta.lattice, so pages/ecosystem-hub.html can
 * show it without re-deriving the eligibility rule itself.
 *
 * _meta deliberately carries no wall-clock timestamp or git commit SHA — Session
 * 022 found a real merge conflict on this exact file caused by two branches each
 * regenerating it with identical underlying data but different build-time
 * metadata. See config/lessons/generated-artifacts-must-be-content-deterministic.json.
 *
 * Pure functions exported for testing:
 *   buildTranslationNotices(manifest, flatEnBundle, supportedLangs, demoScopePrefix)
 *   buildStatusRollup(notices, meta)
 *   countOpen(notices)
 *   buildLatticeCoverage(latticeMap, libWidgetsJsFiles)
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : system health manifest assembler — reads hand-authored status∕*.json plus the strings manifest and key-alignment report, writes data/status.json
 *   reads     : data/strings/compiled/manifest.json
 *               data/strings/compiled/strings.en.json
 *               data/index.json
 *               data/strings/compiled/scopes/demo/ (recursive walk for fixture detection)
 *               data/status/tech-debt.json
 *               data/status/planned-enhancements.json
 *               data/status/assumptions.json
 *               data/status/open-discussions.json
 *               docs/lattice-map.json
 *               lib/ and widgets/ directory listings (.js files, for coverage denominator)
 *               lib/check-key-alignment.js (checkKeyAlignment() — orphan pages, wip collisions/duplicate intents)
 *   writes    : data/status.json
 *   loaded-by : pages/ecosystem-hub.html (live fetch of its output data/status.json)
 *               .github/workflows/build-index.yml (CI, Session 022)
 *               tests/10-build-status.test.js
 *               tests/21-wip-drafts.test.js
 *   tested-by : tests/10-build-status.test.js
 *               tests/21-wip-drafts.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     notice category added/removed:
 *       - lib/build-ecosystem-hub.js (render order array + icon map)
 *       - tests/10 (SAMPLE_NOTICES + assertions)
 *     status∕*.json item schema changed:
 *       - lib/build-ecosystem-hub.js renderHealthPanel() (reads title/description/priority/considerations/etc.)
 *       - tests/10 (required-fields integration tests)
 *     lattice coverage eligibility rule changed:
 *       - lib/build-lattice-headers.js isEligibleNode() (must stay identical or the two coverage numbers disagree)
 *     check-key-alignment.js report shape changed:
 *       - buildContentIntegrityNotices() here reads report.pages.orphans / report.wip.collisions / report.wip.duplicateIntents / report.wip.htmlDrafts directly — a shape change there breaks this silently unless tests/10, tests/08, or tests/21 catch it
 *     any new _meta field being considered:
 *       - must not vary run-to-run for identical source data (no wall-clock timestamp, no git commit SHA) — see config/lessons/generated-artifacts-must-be-content-deterministic.json for why; if a field genuinely needs to reflect build time (like data/index.json's builtAt), that's a deliberate, different tradeoff, not the default
 * LATTICE:END
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT       = path.join(__dirname, '..');
const STATUS_DIR = path.join(ROOT, 'data', 'status');
const STATUS_OUT = path.join(ROOT, 'data', 'status.json');
const COMPILED   = path.join(ROOT, 'data', 'strings', 'compiled');
const INDEX_IN   = path.join(ROOT, 'data', 'index.json');

// ── Pure computation ─────────────────────────────────────────────────────────

/**
 * buildTranslationNotices — finds string keys missing from any supported lang.
 * Demo-category scope keys (pages starting with demoScopePrefix in their scope
 * name where those scopes live under the demo/ compiled dir) are marked
 * intentional: true — they are fixture gaps, not genuine translation debt.
 *
 * Returns an array of notice objects sorted by priority (production first).
 */
function buildTranslationNotices(manifest, flatEnBundle, supportedLangs, demoScopes) {
  const demo  = new Set(demoScopes || []);
  const items = [];

  for (const [key, entry] of Object.entries(manifest)) {
    for (const lang of supportedLangs) {
      if (lang === 'en') continue;
      if (entry.langs.includes(lang)) continue;

      const enVal      = flatEnBundle[key];
      // A key belongs to a demo scope if any demo scope string is a prefix of it.
      // e.g. key 'pages.specimen-partial-translation.body.untranslated'
      //      matches demo scope 'pages.specimen-partial-translation'
      const intentional = [...demo].some(s => key === s || key.startsWith(s + '.'));

      items.push({
        key,
        lang,
        reason:       'missing_translation',
        intentional,
        en: enVal ? (enVal.text || JSON.stringify(enVal)) : null,
      });
    }
  }

  // Production gaps first
  items.sort((a, b) => (a.intentional ? 1 : 0) - (b.intentional ? 1 : 0));
  return items;
}

/**
 * buildContentIntegrityNotices — maps lib/check-key-alignment.js's orphan-page,
 * wip/-collision, and duplicate-wip/-intent findings into the standard notice
 * item shape ({title, description, priority, context}) every other category
 * already uses, so renderHealthPanel() needs no special case for this one.
 * All informational (see check-key-alignment.js's header for why nothing here
 * blocks a build) — priority reflects urgency of attention, not build-blocking.
 */
function buildContentIntegrityNotices(orphanPages, wipCollisions, wipDuplicateIntents, wipHtmlDrafts) {
  const items = [];

  for (const slug of (orphanPages || [])) {
    items.push({
      title:       `Uncurated page: ${slug}`,
      description: `pages/${slug}.html has no data/nodes.json entry — visible via auto-discovery (lib/auto-discover-nodes.js: title scraped from <title>, no date, no arc, department/workType from <meta> tags or the default), not from curated data. Add a real nodes.json entry when you get to it; not urgent.`,
      priority:    'low',
      context:     'uncurated-page',
    });
  }

  for (const { file, slug } of (wipCollisions || [])) {
    items.push({
      title:       `wip/ collision: ${slug}`,
      description: `${file} declares _meta.slug "${slug}", which already exists as a real page. Placing it there would conflict with existing content.`,
      priority:    'high',
      context:     file,
    });
  }

  for (const { slug, files } of (wipDuplicateIntents || [])) {
    items.push({
      title:       `Duplicate wip/ intent: ${slug}`,
      description: `Multiple wip/ files declare the same intended slug: ${files.join(', ')}.`,
      priority:    'medium',
      context:     'wip-duplicate-intent',
    });
  }

  for (const { file, slug, title } of (wipHtmlDrafts || [])) {
    items.push({
      title:       `Draft in wip/: ${title}`,
      description: `wip/${file} has no destination yet (slug: ${slug}, derived from filename). Not a problem — visible here the moment it's added, per lib/auto-discover-nodes.js's discoverWipDrafts, so no manual mapping is needed before it's moved to pages/. Move it to pages/${slug}.html when ready; the same slug carries over automatically.`,
      priority:    'low',
      context:     'wip-html-draft',
    });
  }

  return items;
}

function buildPageBindingNotices(bindingReport) {
  const rows = (bindingReport && bindingReport.rows) || [];
  const summary = (bindingReport && bindingReport.summary) || {};
  const items = [];

  const slugsWhere = predicate => rows.filter(predicate).map(r => r.slug);
  const formatSlugs = slugs => slugs.map(slug => `pages/${slug}.html`).join(', ');

  const blocked = slugsWhere(r => r.state === 'blocked');
  if (blocked.length) {
    items.push({
      title:       `Blocked page bindings: ${blocked.length}`,
      description: `${formatSlugs(blocked)} cannot be wired by the current God Script path yet. These are documented blockers from lib/audit-pages.js, not new failures.`,
      priority:    'high',
      context:     'page-binding-blocked',
    });
  }

  const legacy = slugsWhere(r => r.state === 'legacy-pattern');
  if (legacy.length) {
    items.push({
      title:       `Legacy language/demo widget pattern: ${legacy.length}`,
      description: `${formatSlugs(legacy)} have assembled God Scripts available but still use direct widget script tags. Wire them to dist/vextreme-{slug}.js when the page is next touched.`,
      priority:    'medium',
      context:     'page-binding-legacy-pattern',
    });
  }

  const ready = slugsWhere(r => r.state === 'ready-to-wire');
  if (ready.length) {
    items.push({
      title:       `Ready to wire to God Script: ${ready.length}`,
      description: `${formatSlugs(ready)} already have dist/vextreme-{slug}.js but the HTML does not load it yet.`,
      priority:    'medium',
      context:     'page-binding-ready-to-wire',
    });
  }

  const missing = slugsWhere(r => r.state === 'missing-god-script');
  if (missing.length) {
    items.push({
      title:       `No God Script assembled yet: ${missing.length}`,
      description: `${formatSlugs(missing)} are visible as HTML pages, but lib/build-vextreme.js skipped them because the required string scope bundle is not compiled yet or the page is not curated enough to assemble.`,
      priority:    'low',
      context:     'page-binding-missing-god-script',
    });
  }

  const arcNavMissing = summary.arcNavMountWithoutGodScript || [];
  if (arcNavMissing.length) {
    items.push({
      title:       `Arc-nav mount without God Script binding: ${arcNavMissing.length}`,
      description: `${formatSlugs(arcNavMissing)} include #arcNavMount but are not wired to the God Script path that can carry the v2 arc-nav feature.`,
      priority:    'high',
      context:     'page-binding-arc-nav',
    });
  }

  const i18nMissing = summary.i18nBindingsWithoutLangLoader || [];
  if (i18nMissing.length) {
    items.push({
      title:       `i18n bindings without language loader: ${i18nMissing.length}`,
      description: `${formatSlugs(i18nMissing)} include data-i18n attributes but do not appear to load the language feature, so translations cannot apply at runtime.`,
      priority:    'high',
      context:     'page-binding-i18n-loader',
    });
  }

  return items;
}

/**
 * buildStatusRollup — assembles the full status.json object from notice arrays.
 * meta.lattice, if provided (see buildLatticeCoverage), is passed through to _meta.
 *
 * Deliberately excludes any wall-clock timestamp or git commit SHA — see
 * config/lessons/generated-artifacts-must-be-content-deterministic.json.
 * Two builds from identical underlying source data must produce a
 * byte-identical file, so an unrelated branch/PR regenerating this file
 * never manufactures a merge conflict out of metadata nothing reads.
 */
function buildStatusRollup(notices, meta) {
  const { translation, techDebt, enhancements, assumptions, openDiscussions, contentIntegrity } = notices;

  const genuinePending = (translation || []).filter(t => !t.intentional);

  return {
    _meta: {
      totalOpen:   countOpen({ translation: genuinePending, techDebt, enhancements, assumptions, openDiscussions, contentIntegrity }),
      lattice:     meta.lattice    || null,
    },
    notices: {
      translation: {
        label:         'Needs Translation',
        autoGenerated: true,
        count:         genuinePending.length,
        items:         genuinePending,
        fixtures:      (translation || []).filter(t => t.intentional),
      },
      techDebt: {
        label:         'Tech Debt',
        autoGenerated: false,
        count:         (techDebt || []).length,
        items:         techDebt || [],
      },
      enhancements: {
        label:         'Planned Enhancements',
        autoGenerated: false,
        count:         (enhancements || []).length,
        items:         enhancements || [],
      },
      assumptions: {
        label:         'Unverified Assumptions',
        autoGenerated: false,
        count:         (assumptions || []).length,
        items:         assumptions || [],
      },
      openDiscussions: {
        label:         'Open Discussions',
        autoGenerated: false,
        count:         (openDiscussions || []).length,
        items:         openDiscussions || [],
      },
      contentIntegrity: {
        label:         'Content Integrity',
        autoGenerated: true,
        count:         (contentIntegrity || []).length,
        items:         contentIntegrity || [],
      },
    },
  };
}

/**
 * countOpen — total open items across all categories.
 * Translation fixtures are excluded (intentional, not debt).
 */
function countOpen(notices) {
  return (
    (notices.translation      || []).filter(t => !t.intentional).length +
    (notices.techDebt         || []).length +
    (notices.enhancements     || []).length +
    (notices.assumptions      || []).length +
    (notices.openDiscussions  || []).length +
    (notices.contentIntegrity || []).length
  );
}

/**
 * buildLatticeCoverage — mapped vs. total eligible .js files in lib/+widgets/.
 * "Eligible" mirrors lib/build-lattice-headers.js's isEligibleNode: ends in
 * .js, not sw.js, not under dist/. latticeMap is the parsed lattice-map.json;
 * libWidgetsJsFiles is every .js file path (repo-relative, e.g. 'lib/foo.js')
 * found under lib/ and widgets/.
 */
function buildLatticeCoverage(latticeMap, libWidgetsJsFiles) {
  const isEligible = (file) => file.endsWith('.js') && file !== 'sw.js' && !file.startsWith('dist/');
  const mappedNodes = Object.keys((latticeMap && latticeMap.nodes) || {}).filter(isEligible);
  const totalFiles  = (libWidgetsJsFiles || []).filter(isEligible);

  return {
    mappedNodes: mappedNodes.length,
    totalFiles:  totalFiles.length,
    coveragePct: totalFiles.length ? Math.round((mappedNodes.length / totalFiles.length) * 100) : 0,
  };
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const manifest     = JSON.parse(fs.readFileSync(path.join(COMPILED, 'manifest.json'), 'utf8'));
  const flatEn       = JSON.parse(fs.readFileSync(path.join(COMPILED, 'strings.en.json'), 'utf8'));
  const index        = JSON.parse(fs.readFileSync(INDEX_IN, 'utf8'));
  const supportedLangs = index.supportedLangs || ['en', 'ja'];

  // Demo scopes: walk data/strings/compiled/scopes/demo/ recursively,
  // converting path separators to dots to get the scope name.
  // e.g. pages/specimen-partial-translation.en.json → pages.specimen-partial-translation
  const demoScopesDir = path.join(COMPILED, 'scopes', 'demo');
  const demoScopes    = [];
  (function walk(dir, prefix) {
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (fs.statSync(full).isDirectory()) {
        walk(full, prefix ? `${prefix}.${entry}` : entry);
      } else if (entry.endsWith('.en.json')) {
        demoScopes.push((prefix ? `${prefix}.` : '') + entry.replace(/\.en\.json$/, ''));
      }
    }
  }(demoScopesDir, ''));

  const techDebt        = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'tech-debt.json'),            'utf8')).items;
  const enhancements    = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'planned-enhancements.json'), 'utf8')).items;
  const assumptions     = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'assumptions.json'),          'utf8')).items;
  const openDiscussions = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'open-discussions.json'),     'utf8')).items;

  // Lattice coverage: docs/lattice-map.json nodes vs. every .js file under lib/+widgets/.
  const latticeMap = JSON.parse(fs.readFileSync(path.join(ROOT, 'docs', 'lattice-map.json'), 'utf8'));
  const libWidgetsJsFiles = [];
  for (const dir of ['lib', 'widgets']) {
    for (const entry of fs.readdirSync(path.join(ROOT, dir))) {
      if (entry.endsWith('.js')) libWidgetsJsFiles.push(`${dir}/${entry}`);
    }
  }
  const lattice = buildLatticeCoverage(latticeMap, libWidgetsJsFiles);

  const { checkKeyAlignment } = require('./check-key-alignment');
  const alignment      = checkKeyAlignment();
  const contentIntegrity = buildContentIntegrityNotices(
    alignment.pages.orphans,
    alignment.wip.collisions,
    alignment.wip.duplicateIntents,
    alignment.wip.htmlDrafts
  ).concat(buildPageBindingNotices(alignment.pages.bindings));

  const translation = buildTranslationNotices(manifest, flatEn, supportedLangs, demoScopes);
  const rollup      = buildStatusRollup(
    { translation, techDebt, enhancements, assumptions, openDiscussions, contentIntegrity },
    { lattice }
  );

  fs.writeFileSync(STATUS_OUT, JSON.stringify(rollup, null, 2));

  const { notices: n } = rollup;
  console.log('[build-status] Done.');
  console.log(`  translation      : ${n.translation.count} pending, ${n.translation.fixtures.length} intentional fixtures`);
  console.log(`  tech debt        : ${n.techDebt.count} items`);
  console.log(`  enhancements     : ${n.enhancements.count} items`);
  console.log(`  assumptions      : ${n.assumptions.count} items`);
  console.log(`  open discussions : ${n.openDiscussions.count} items`);
  console.log(`  content integrity: ${n.contentIntegrity.count} items`);
  console.log(`  lattice coverage : ${lattice.mappedNodes}/${lattice.totalFiles} (${lattice.coveragePct}%)`);
  console.log(`  total open       : ${rollup._meta.totalOpen}`);
  console.log(`  output           : ${STATUS_OUT}`);
}

module.exports = { buildTranslationNotices, buildStatusRollup, countOpen, buildLatticeCoverage, buildContentIntegrityNotices, buildPageBindingNotices };

// [VXG RealForever]
