#!/usr/bin/env node
/**
 * VEXTREME — lib/build-sw.js
 *
 * Generates sw.js at repo root. Reads dist/ to collect all assembled God
 * Script URLs, injects the current git commit hash as the cache version,
 * and writes the complete Service Worker file.
 *
 * Cache naming: vextreme-v1-{git-short-hash}
 * The hash changes every commit → old caches are automatically invalidated
 * without requiring a manual version bump.
 *
 * Run manually:   node lib/build-sw.js
 * Auto-run via:   after build-vextreme.js (not yet wired into CI — follow-up item)
 *
 * Pure functions exported for testing:
 *   collectDistUrls(distDir) → string[]
 *   generateSWContent(godScriptUrls, commitHash) → string
 *   getCommitHash() → string
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : Service Worker generator — reads dist/ filenames, writes sw.js
 *   reads     : dist∕*.js (all God Script filenames)
 *               git commit hash
 *   writes    : sw.js
 *   loaded-by : .github/workflows/build-index.yml
 *   tested-by : tests/09-build-sw.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     CORE_ASSETS list:
 *       - styles/design-system.css, styles/arc-nav.css, data/index.json (must exist at these paths)
 *       - tests/09 (asserts each core asset)
 *     cache name format:
 *       - sw.js activate handler (cleans caches by name pattern)
 *       - tests/09
 * LATTICE:END
 */

'use strict';

const fs           = require('fs');
const path         = require('path');
const { execSync } = require('child_process');

const ROOT     = path.join(__dirname, '..');
const DIST_DIR = path.join(ROOT, 'dist');
const SW_OUT   = path.join(ROOT, 'sw.js');

// Core assets pre-cached on every page, alongside the per-page God Scripts.
// These are shared stylesheets and the index data file — all cacheable with
// long TTLs since they change only when the build runs.
const CORE_ASSETS = [
  '/Vextreme/styles/design-system.css',
  '/Vextreme/styles/arc-nav.css',
  '/Vextreme/data/index.json',
];

// ── Pure computation functions ────────────────────────────────────────────────

// getCommitHash — returns the current short git commit hash.
// Falls back to 'dev' in environments without git (unit tests, etc.).
function getCommitHash() {
  try {
    return execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim();
  } catch (e) {
    return 'dev';
  }
}

// collectDistUrls — lists all assembled God Script URLs from dist/.
// Paths are absolute GitHub Pages URLs so the SW can cache them by origin.
function collectDistUrls(distDir) {
  try {
    return fs.readdirSync(distDir)
      .filter(f => /^vextreme-.+\.js$/.test(f))
      .sort()
      .map(f => `/Vextreme/dist/${f}`);
  } catch (e) {
    return [];
  }
}

// generateSWContent — assembles the complete sw.js string.
// commitHash is injected into the cache name so each build gets a fresh cache.
function generateSWContent(godScriptUrls, commitHash) {
  const cacheName = `vextreme-v1-${commitHash || 'dev'}`;
  const allUrls   = [...godScriptUrls, ...CORE_ASSETS];

  return [
    `/* VEXTREME — sw.js`,
    ` * Service Worker. Generated by lib/build-sw.js.`,
    ` * DO NOT EDIT — regenerate with: node lib/build-sw.js`,
    ` * Cache: ${cacheName}`,
    ` */`,
    `'use strict';`,
    ``,
    `var CACHE_NAME    = '${cacheName}';`,
    `var PRECACHE_URLS = ${JSON.stringify(allUrls, null, 2)};`,
    ``,
    `/* On install: pre-cache all known assets. */`,
    `self.addEventListener('install', function (event) {`,
    `  event.waitUntil(`,
    `    caches.open(CACHE_NAME).then(function (cache) {`,
    `      return cache.addAll(PRECACHE_URLS);`,
    `    }).then(function () {`,
    `      return self.skipWaiting(); // take control immediately`,
    `    })`,
    `  );`,
    `});`,
    ``,
    `/* On activate: delete caches from all previous versions. */`,
    `self.addEventListener('activate', function (event) {`,
    `  event.waitUntil(`,
    `    caches.keys().then(function (keys) {`,
    `      return Promise.all(`,
    `        keys`,
    `          .filter(function (key) { return key !== CACHE_NAME; })`,
    `          .map(function (key)    { return caches.delete(key); })`,
    `      );`,
    `    }).then(function () {`,
    `      return self.clients.claim();`,
    `    })`,
    `  );`,
    `});`,
    ``,
    `/* On fetch: cache-first for pre-cached assets, network for everything else.`,
    ` * HTML pages are NEVER intercepted — they must always be fresh.`,
    ` * Non-GET requests pass through untouched. */`,
    `self.addEventListener('fetch', function (event) {`,
    `  if (event.request.method !== 'GET') return;`,
    ``,
    `  var accept = event.request.headers.get('accept') || '';`,
    `  if (accept.indexOf('text/html') !== -1) return; // HTML: always fresh`,
    ``,
    `  event.respondWith(`,
    `    caches.match(event.request).then(function (cached) {`,
    `      if (cached) return cached;`,
    ``,
    `      return fetch(event.request).then(function (response) {`,
    `        if (!response || response.status !== 200 || response.type === 'opaque') {`,
    `          return response;`,
    `        }`,
    `        var toCache = response.clone();`,
    `        caches.open(CACHE_NAME).then(function (cache) {`,
    `          cache.put(event.request, toCache);`,
    `        });`,
    `        return response;`,
    `      });`,
    `    })`,
    `  );`,
    `});`,
    ``,
    `// [VXG RealForever]`,
  ].join('\n');
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const commitHash    = getCommitHash();
  const godScriptUrls = collectDistUrls(DIST_DIR);
  const content       = generateSWContent(godScriptUrls, commitHash);

  fs.writeFileSync(SW_OUT, content);

  console.log(`[build-sw] Done.`);
  console.log(`  cache   : vextreme-v1-${commitHash}`);
  console.log(`  scripts : ${godScriptUrls.length} God Scripts`);
  console.log(`  core    : ${CORE_ASSETS.length} shared assets`);
  console.log(`  total   : ${godScriptUrls.length + CORE_ASSETS.length} pre-cached URLs`);
  console.log(`  output  : ${SW_OUT}`);
}

module.exports = { collectDistUrls, generateSWContent, getCommitHash, CORE_ASSETS };

// [VXG RealForever]
