#!/usr/bin/env node
/**
 * VEXTREME — lib/build-status.js
 *
 * Assembles data/status.json — the system health manifest.
 *
 * Four notice categories:
 *   translation  — auto-generated from strings/compiled/manifest.json
 *                  keys missing from any supported language (excluding demo
 *                  category pages where gaps are intentional fixtures)
 *   techDebt     — hand-authored in data/status/tech-debt.json
 *   enhancements — hand-authored in data/status/planned-enhancements.json
 *   assumptions  — hand-authored in data/status/assumptions.json
 *
 * Pure functions exported for testing:
 *   buildTranslationNotices(manifest, flatEnBundle, supportedLangs, demoScopePrefix)
 *   buildStatusRollup(notices, meta)
 *   countOpen(notices)
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT       = path.join(__dirname, '..');
const STATUS_DIR = path.join(ROOT, 'data', 'status');
const STATUS_OUT = path.join(ROOT, 'data', 'status.json');
const COMPILED   = path.join(ROOT, 'data', 'strings', 'compiled');
const INDEX_IN   = path.join(ROOT, 'data', 'index.json');

// ── Pure computation ─────────────────────────────────────────────────────────

/**
 * buildTranslationNotices — finds string keys missing from any supported lang.
 * Demo-category scope keys (pages starting with demoScopePrefix in their scope
 * name where those scopes live under the demo/ compiled dir) are marked
 * intentional: true — they are fixture gaps, not genuine translation debt.
 *
 * Returns an array of notice objects sorted by priority (production first).
 */
function buildTranslationNotices(manifest, flatEnBundle, supportedLangs, demoScopes) {
  const demo  = new Set(demoScopes || []);
  const items = [];

  for (const [key, entry] of Object.entries(manifest)) {
    for (const lang of supportedLangs) {
      if (lang === 'en') continue;
      if (entry.langs.includes(lang)) continue;

      const enVal      = flatEnBundle[key];
      // A key belongs to a demo scope if any demo scope string is a prefix of it.
      // e.g. key 'pages.specimen-partial-translation.body.untranslated'
      //      matches demo scope 'pages.specimen-partial-translation'
      const intentional = [...demo].some(s => key === s || key.startsWith(s + '.'));

      items.push({
        key,
        lang,
        reason:       'missing_translation',
        intentional,
        en: enVal ? (enVal.text || JSON.stringify(enVal)) : null,
      });
    }
  }

  // Production gaps first
  items.sort((a, b) => (a.intentional ? 1 : 0) - (b.intentional ? 1 : 0));
  return items;
}

/**
 * buildStatusRollup — assembles the full status.json object from notice arrays.
 */
function buildStatusRollup(notices, meta) {
  const { translation, techDebt, enhancements, assumptions } = notices;

  const genuinePending = (translation || []).filter(t => !t.intentional);

  return {
    _meta: {
      generated:   meta.generated  || new Date().toISOString(),
      commit:      meta.commit     || 'unknown',
      totalOpen:   countOpen({ translation: genuinePending, techDebt, enhancements, assumptions }),
    },
    notices: {
      translation: {
        label:         'Needs Translation',
        autoGenerated: true,
        count:         genuinePending.length,
        items:         genuinePending,
        fixtures:      (translation || []).filter(t => t.intentional),
      },
      techDebt: {
        label:         'Tech Debt',
        autoGenerated: false,
        count:         (techDebt || []).length,
        items:         techDebt || [],
      },
      enhancements: {
        label:         'Planned Enhancements',
        autoGenerated: false,
        count:         (enhancements || []).length,
        items:         enhancements || [],
      },
      assumptions: {
        label:         'Unverified Assumptions',
        autoGenerated: false,
        count:         (assumptions || []).length,
        items:         assumptions || [],
      },
    },
  };
}

/**
 * countOpen — total open items across all categories.
 * Translation fixtures are excluded (intentional, not debt).
 */
function countOpen(notices) {
  return (
    (notices.translation  || []).filter(t => !t.intentional).length +
    (notices.techDebt     || []).length +
    (notices.enhancements || []).length +
    (notices.assumptions  || []).length
  );
}

// ── I/O — only runs when executed directly ────────────────────────────────────

if (require.main === module) {
  const manifest     = JSON.parse(fs.readFileSync(path.join(COMPILED, 'manifest.json'), 'utf8'));
  const flatEn       = JSON.parse(fs.readFileSync(path.join(COMPILED, 'strings.en.json'), 'utf8'));
  const index        = JSON.parse(fs.readFileSync(INDEX_IN, 'utf8'));
  const supportedLangs = index.supportedLangs || ['en', 'ja'];

  // Demo scopes: walk data/strings/compiled/scopes/demo/ recursively,
  // converting path separators to dots to get the scope name.
  // e.g. pages/specimen-partial-translation.en.json → pages.specimen-partial-translation
  const demoScopesDir = path.join(COMPILED, 'scopes', 'demo');
  const demoScopes    = [];
  (function walk(dir, prefix) {
    for (const entry of fs.readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (fs.statSync(full).isDirectory()) {
        walk(full, prefix ? `${prefix}.${entry}` : entry);
      } else if (entry.endsWith('.en.json')) {
        demoScopes.push((prefix ? `${prefix}.` : '') + entry.replace(/\.en\.json$/, ''));
      }
    }
  }(demoScopesDir, ''));

  const techDebt    = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'tech-debt.json'),            'utf8')).items;
  const enhancements = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'planned-enhancements.json'), 'utf8')).items;
  const assumptions  = JSON.parse(fs.readFileSync(path.join(STATUS_DIR, 'assumptions.json'),          'utf8')).items;

  const { execSync } = require('child_process');
  let commit = 'unknown';
  try { commit = execSync('git rev-parse --short HEAD', { cwd: ROOT, encoding: 'utf8' }).trim(); } catch (_) {}

  const translation = buildTranslationNotices(manifest, flatEn, supportedLangs, demoScopes);
  const rollup      = buildStatusRollup(
    { translation, techDebt, enhancements, assumptions },
    { commit }
  );

  fs.writeFileSync(STATUS_OUT, JSON.stringify(rollup, null, 2));

  const { notices: n } = rollup;
  console.log('[build-status] Done.');
  console.log(`  translation  : ${n.translation.count} pending, ${n.translation.fixtures.length} intentional fixtures`);
  console.log(`  tech debt    : ${n.techDebt.count} items`);
  console.log(`  enhancements : ${n.enhancements.count} items`);
  console.log(`  assumptions  : ${n.assumptions.count} items`);
  console.log(`  total open   : ${rollup._meta.totalOpen}`);
  console.log(`  output       : ${STATUS_OUT}`);
}

module.exports = { buildTranslationNotices, buildStatusRollup, countOpen };

// [VXG RealForever]
