'use strict';

// Structured logger for Node build scripts.
//
// Each call takes a single event object: { code, message, ...optionalFields }
// Optional fields (arc, slug, key, file, langs, error, status, etc.) are
// attached without changing the call signature — add new fields at any call
// site without touching any other.
//
// To swap the backing store (e.g. write to a DB instead of console):
//   const { logger } = require('./logger');
//   logger.warn = event => db.insert('build_events', { ...event, ts: Date.now() });
//
// LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
//   role      : structured logger — every build script's warn/info/error call goes through here
//   reads     : (none)
//   writes    : stdout/stderr via console.warn/log/error
//   loaded-by : lib/build-index.js
//               lib/build-vextreme.js
//               lib/build-lattice-headers.js
//               lib/strings-compile.js
//               lib/strings-check.js
//               every other lib/build-*.js and lib/check-*.js script that logs a warning
//   tested-by : (none)
//
//   CHANGE MAP — if you touch X here, also check:
//     logger method signature changed (warn/info/error):
//       - every call site across lib/ — all follow the same { code, message, ...fields } shape; a signature change ripples everywhere at once
//     backing store swapped (e.g. console → DB):
//       - no call site needs to change — that's the point of the single indirection point here
// LATTICE:END

const logger = {
  warn(event) {
    console.warn(`[${event.code}]`, event.message, omit(event, ['code', 'message']));
  },
  info(event) {
    console.log(`[${event.code}]`, event.message, omit(event, ['code', 'message']));
  },
  error(event) {
    console.error(`[${event.code}]`, event.message, omit(event, ['code', 'message']));
  },
};

function omit(obj, keys) {
  const out = {};
  for (const [k, v] of Object.entries(obj)) {
    if (!keys.includes(k)) out[k] = v;
  }
  return out;
}

module.exports = { logger };

// [VXG RealForever]
