/**
 * VEXTREME — lib/shell.js
 *
 * GitHub Pages bootstrap. Add ONE script tag to each page:
 *
 *   <script src="https://cdn.jsdelivr.net/gh/vgong24/vextreme@main/lib/shell.js"></script>
 *
 * NO version number in the page's script tag. shell.js is stable and
 * minimal — it only loads vextreme.js. The version that matters is on
 * vextreme.js (below), which controls all downstream asset cache busting.
 *
 * TO UPDATE ASSETS: bump VEXTREME_VER below and in vextreme.js DEFAULT_CACHE.
 * Push both files. Every page picks up the new version automatically —
 * no page HTML needs to be touched.
 *
 * OVERRIDES (rare — declare before shell.js loads):
 *   <script>window.VEXTREME_OVERRIDE = { slug: 'different-slug' };</script>
 *   <script src=".../shell.js"></script>
 *
 * FORK USAGE:
 *   <script>window.VEXTREME_OVERRIDE = { baseUrl: 'https://cdn.jsdelivr.net/gh/yourname/yourrepo@main' };</script>
 *   <script src="[your fork shell.js]"></script>
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : thin GitHub Pages shell bootstrap — loads the cache-versioned legacy runtime and invokes VEXTREME with the page's optional override
 *   reads     : lib/vextreme.js (cache-versioned runtime loaded into the page)
 *               window.VEXTREME_OVERRIDE (optional page configuration passed through after load)
 *   writes    : DOM script element for lib/vextreme.js
 *               window.VEXTREME invocation after the runtime loads
 *   loaded-by : pages∕*.html (shell consumers; template edge)
 *               lib/build-specimens.js (emits the shared shell tag for generated specimen pages)
 *   tested-by : tests/41-vextreme-fab-autoload.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     VEXTREME_VER or bootstrap cache handoff changed:
 *       - lib/vextreme.js DEFAULT_CACHE (must stay byte-equivalent as a version token)
 *       - tests/41-vextreme-fab-autoload.test.js (CACHE-SYNC assertion)
 *     runtime target or VEXTREME invocation contract changed:
 *       - lib/vextreme.js (the loaded runtime/entry point)
 *       - shell-consuming pages and generators using the one-tag bootstrap
 * LATTICE:END
 */

(function () {
  'use strict';

  var BASE = 'https://cdn.jsdelivr.net/gh/vgong24/vextreme@main';

  // Version lives here and in vextreme.js DEFAULT_CACHE.
  // Bump both together when any asset changes. Pages never need updating.
  var VEXTREME_VER = '?v=8';

  var el    = document.createElement('script');
  el.src    = BASE + '/lib/vextreme.js' + VEXTREME_VER;
  el.onload = function () {
    if (typeof window.VEXTREME === 'function') {
      // Pass override config if declared, otherwise call with no args
      window.VEXTREME(window.VEXTREME_OVERRIDE || {});
    } else {
      console.warn('[VEXTREME shell] vextreme.js loaded but VEXTREME not defined');
    }
  };
  el.onerror = function () {
    console.warn('[VEXTREME shell] Failed to load vextreme.js from: ' + el.src);
  };
  document.head.appendChild(el);

}());
