'use strict';

/**
 * VEXTREME - lib/terrain-journey.js
 *
 * Pure semantic-history state for the Terrain Map. The browser page owns
 * rendering and history navigation; this module owns the namespaced,
 * serializable journey shape so Back/Forward restoration can be tested
 * without a DOM.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : pure semantic-history state for Terrain Journey commits and browser Back/Forward restoration
 *   reads     : (none)
 *   writes    : (none)
 *   loaded-by : pages/terrain-map.html (browser script before the page's inline interaction layer)
 *               tests/45-terrain-journey.test.js (CommonJS pure-state coverage)
 *   tested-by : tests/45-terrain-journey.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     snapshot namespace, version, semantic fields, or journey entry shape changed:
 *       - pages/terrain-map.html (capture, restore, Journey drawer, and popstate integration)
 *       - tests/45-terrain-journey.test.js
 *     append/reset branching semantics changed:
 *       - browser Back/Forward, Return to origin, and Clear journey behavior in pages/terrain-map.html
 * LATTICE:END
 */

(function (root, factory) {
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.VextremeTerrainJourney = api;
}(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  var STATE_KEY = 'vextremeTerrainJourney';
  var VERSION = 1;

  function copy(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function normalizeEntry(entry) {
    return {
      label: String(entry.label || 'Terrain'),
      nodeId: entry.nodeId || null,
      fromNodeId: entry.fromNodeId || null,
      relationship: entry.relationship || null,
      reason: entry.reason || null,
      world: entry.world || 'code',
      level: entry.level || 'system',
    };
  }

  function create(semantic, originEntry, generation) {
    return {
      version: VERSION,
      generation: generation || 0,
      semantic: copy(semantic),
      journey: {
        cursor: 0,
        entries: [normalizeEntry(originEntry)],
      },
    };
  }

  function append(snapshot, semantic, entry) {
    var entries = snapshot.journey.entries.slice(0, snapshot.journey.cursor + 1);
    entries.push(normalizeEntry(entry));
    return {
      version: VERSION,
      generation: snapshot.generation || 0,
      semantic: copy(semantic),
      journey: {
        cursor: entries.length - 1,
        entries: entries,
      },
    };
  }

  function reset(snapshot, semantic, entry) {
    return create(semantic, entry || snapshot.journey.entries[snapshot.journey.cursor], (snapshot.generation || 0) + 1);
  }

  function sameSemantic(left, right) {
    return JSON.stringify(left || null) === JSON.stringify(right || null);
  }

  function wrap(snapshot, priorState) {
    var state = priorState && typeof priorState === 'object' ? copy(priorState) : {};
    state[STATE_KEY] = copy(snapshot);
    return state;
  }

  function unwrap(state) {
    var snapshot = state && state[STATE_KEY];
    if (!snapshot || snapshot.version !== VERSION || !snapshot.semantic || !snapshot.journey) return null;
    if (typeof snapshot.generation !== 'number') return null;
    if (!Array.isArray(snapshot.journey.entries) || typeof snapshot.journey.cursor !== 'number') return null;
    return copy(snapshot);
  }

  function current(snapshot) {
    return snapshot.journey.entries[snapshot.journey.cursor] || null;
  }

  return {
    STATE_KEY: STATE_KEY,
    VERSION: VERSION,
    create: create,
    append: append,
    reset: reset,
    sameSemantic: sameSemantic,
    wrap: wrap,
    unwrap: unwrap,
    current: current,
  };
}));

// [VXG RealForever]
