/**
 * VEXTREME — lib/vex-config.js
 *
 * Single source of truth for all semantic constants in the build system and
 * browser runtime. No build script, no widget, no generated page should contain
 * a hardcoded semantic string — everything flows from here.
 *
 * Usage (Node.js build scripts):
 *   const { Category, Language, Scope, Path } = require('./vex-config');
 *   const cat = Category.DEMO;  // 'demo'
 *
 * Usage (browser runtime, widgets):
 *   Constants are bundled inline by the build scripts that generate pages.
 *   lang-fab.js reads window.VEX_STRING_CATEGORY / window.VEX_STRING_SCOPES
 *   which are emitted by build scripts using these constants.
 *
 * End-state note (Session 009):
 *   In a future PR, vextreme.js will read slug → slugMap → { category, scopes,
 *   features } from data/index.json and eliminate the per-page window globals
 *   entirely. This file provides the named constant layer that makes that
 *   transition safe — every reference to 'demo', 'ja', 'common' etc. is
 *   already one Ctrl+click away rather than a grep hunt.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : constants hub — pure declarations, no I/O
 *   reads     : (none)
 *   writes    : (none)
 *   loaded-by : lib/build-index.js
 *               lib/build-vextreme.js
 *               lib/strings-compile.js
 *               lib/strings-check.js
 *               lib/strings-export.js
 *               lib/strings-import.js
 *               lib/build-archives.js
 *               lib/build-specimens.js
 *               lib/validate-blueprint.js
 *               tests/05-vex-config.test.js
 *               tests/06-blueprint.test.js
 *               tests/07-viewmodel.test.js
 *               tests/08-build-vextreme.test.js (FAB SYSTEM propagation tests — reads Feature.* constants directly)
 *               lib/build-demo.js
 *               lib/build-arc-bundles.js
 *   tested-by : tests/05-vex-config.test.js
 *               tests/06-blueprint.test.js
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     Feature.* added/renamed:
 *       - blueprint.json (features array)
 *       - config/features/{id}.json (create if new)
 *       - lib/build-vextreme.js (FEATURES registry)
 *       - tests/06-blueprint.test.js (coverage check)
 *     Category.* added/renamed:
 *       - blueprint.json (categories array)
 *       - config/categories/{id}.json (create if new)
 *       - data/strings/source/ (_meta.category values in source files)
 *       - lib/strings-compile.js (path derivation logic)
 *     Language.* added:
 *       - lib/strings-compile.js
 *       - lib/strings-check.js
 *       - data/status/tech-debt.json (td-006 trigger condition)
 *     scopeRelPath() logic changed:
 *       - widgets/fab-lang.js (applies the same rule at runtime — must stay identical or fetches 404)
 *       - lib/strings-compile.js (applies rule at write time)
 * LATTICE:END
 */

'use strict';

// ── Content lifecycle categories ──────────────────────────────────────────────
// Maps to scopes/{category}/ in the compiled output.
// Mirrors _meta.category in string source files.

const Category = {
  SYSTEM:       'system',       // Infrastructure strings (common). Always loaded.
  PRODUCTION:   'production',   // Real content pages. Default for source files without explicit _meta.category.
  DEMO:         'demo',         // Architecture reference / teaching fixtures.
  STAGING:      'staging',      // In-progress content. Direct-link only, not indexed.
  EXPERIMENTAL: 'experimental', // R&D. Branch-only, never committed to main.
};

// The default category for source files and pages that don't declare one.
const DEFAULT_CATEGORY = Category.PRODUCTION;

// ── Supported languages ───────────────────────────────────────────────────────

const Language = {
  EN: 'en',  // Source language. Always complete.
  JA: 'ja',  // Primary translation target.
  ZH: 'zh',  // Third language (Session 025) — see docs/architecture/06-i18n.md
             // "Arc-chunked bundling pilot" for why it did not just get bolted
             // onto the per-scope-combo model (td-006/od-001).
};

// The source/fallback language. Used when a requested language has no entry.
const DEFAULT_LANGUAGE = Language.EN;

// ── Features ──────────────────────────────────────────────────────────────────
// Matches config/features/{id}.json. Each feature is a self-contained unit of
// browser behavior (language selector, demo nav, theme switcher, spiral FAB).
// In the God Script architecture these are inlined per-page by build-vextreme.js.

const Feature = {
  SW:         'sw',           // Service Worker registration — default: true (core module, not opt-in)
  SPIRAL_FAB: 'spiral-fab',   // orb-group trigger + container — must register before LANG/THEME/MAP below
                               // so its DOMContentLoaded handler creates #vex-spiral-group first (see
                               // lib/build-vextreme.js's FEATURES object — key order there is script
                               // concatenation order, which is the DOMContentLoaded firing order)
  LANG:       'lang',
  THEME:      'theme',
  MAP:        'map',          // orb linking to pages/terrain-map.html
  DEMO:       'demo',
  ARC_NAV:    'arc-nav',      // Arc navigation (prev/next, position in arc) — unblocks content node pages
};

// ── Asset types ───────────────────────────────────────────────────────────────
// Matches config/asset-types/{id}.json. Defines how a feature's asset is loaded.

const AssetType = {
  SCRIPT: 'script',
  STYLE:  'style',
};

// ── Named scopes ──────────────────────────────────────────────────────────────
// Scopes used by more than one file — give them names so callers don't repeat
// the string literal. Page-specific scopes (pages.foo) are typically inlined
// where used; only shared scopes go here.

const Scope = {
  COMMON:    'common',    // Shared UI chrome. Lives in system/. Always fetched.
  DEMO:      'demo',      // Demo page strings.
  SPECIMENS: 'specimens', // Specimens dashboard chrome.
  ARCHIVES:  'archives',  // Archives dashboard strings.
  ARCS:      'arcs',      // Arc nav strings.
};

// ── CDN and path constants ────────────────────────────────────────────────────

const CDN_BASE = 'https://cdn.jsdelivr.net/gh/vgong24/vextreme@main';

const Path = {
  // Source (write-side)
  STRINGS_SOURCE:   'data/strings/source',

  // Compiled (read-side, generated)
  STRINGS_COMPILED: 'data/strings/compiled',
  SCOPES_DIR:       'data/strings/compiled/scopes',
  MANIFEST:         'data/strings/compiled/manifest.json',

  // Pages and output
  PAGES:   'pages',
  WIDGETS: 'widgets',
  STYLES:  'styles',
  CONFIG:  'config',
  DIST:    'dist',

  // CDN
  CDN_BASE,
};

// ── Browser window global names ───────────────────────────────────────────────
// Names of the window properties that pages set before loading lang-fab.js.
// In the future slug-driven architecture these will be eliminated; the loader
// will derive category + scopes from the slugMap in data/index.json.

const WindowGlobal = {
  SCOPES:   'VEX_STRING_SCOPES',   // string[] — scope names to fetch
  CATEGORY: 'VEX_STRING_CATEGORY', // string   — page content lifecycle category
  VARIANT:  'VEX_STRING_VARIANT',  // string?  — A/B variant suffix (optional)
};

// ── Path derivation ───────────────────────────────────────────────────────────
// Derives the relative path within scopes/ for a given scope + category.
// Dots in scope names become directory segments: 'pages.foo' → 'pages/foo'.
// 'common' always routes to system/ regardless of the caller's category.
//
// This rule is applied identically in:
//   - lib/strings-compile.js (build time: write output path)
//   - widgets/lang-fab.js    (runtime: construct fetch URL)
// Keeping one canonical implementation here prevents the two from drifting.

function scopeRelPath(scope, category) {
  const cat  = (scope === Scope.COMMON) ? Category.SYSTEM : (category || DEFAULT_CATEGORY);
  const segs = scope.split('.');
  return [cat, ...segs.slice(0, -1), segs[segs.length - 1]].join('/');
}

// Full CDN URL for a compiled scope bundle.
function scopeUrl(scope, category, lang, cdnBase) {
  return (cdnBase || CDN_BASE)
    + '/' + Path.SCOPES_DIR + '/'
    + scopeRelPath(scope, category) + '.' + lang + '.json';
}

// Full CDN URL for the flat bundle (legacy / default path).
function flatBundleUrl(lang, cdnBase) {
  return (cdnBase || CDN_BASE)
    + '/' + Path.STRINGS_COMPILED + '/strings.' + lang + '.json';
}

// ── Exports ───────────────────────────────────────────────────────────────────

module.exports = {
  Category,
  DEFAULT_CATEGORY,
  Language,
  DEFAULT_LANGUAGE,
  Feature,
  AssetType,
  Scope,
  Path,
  CDN_BASE,
  WindowGlobal,
  scopeRelPath,
  scopeUrl,
  flatBundleUrl,
};

// [VXG RealForever]
