#!/usr/bin/env node
/**
 * VEXTREME — scripts/screenshot-page.js
 *
 * Takes before/after screenshots of a page with the lang-fab widget.
 * Intercepts CDN requests and routes them to local files so the branch
 * version of all JS/data is tested, not whatever is on @main.
 *
 * Usage:
 *   node scripts/screenshot-page.js [slug] [lang] [--assets-root ../Vextreme-Assets]
 *
 *   slug         — page slug under pages/ (default: claude-answers-the-doubt)
 *   lang         — language to switch to for the "after" shot (default: ja)
 *   --assets-root — optional checkout of vgong24/Vextreme-Assets. When supplied,
 *                   each captured PNG is also ingested into its structured
 *                   evidence/screenshots namespace without changing the local
 *                   docs/screenshots output current Vextreme readers consume.
 *
 * Output:
 *   docs/screenshots/{slug}-en.png   — page in default language
 *   docs/screenshots/{slug}-{lang}.png — page after lang-fab switch
 *
 * Run from repo root.
 *
 * LATTICE:BEGIN — generated by lib/build-lattice-headers.js from docs/lattice-map.json. Do not hand-edit; edit the JSON and regenerate.
 *   role      : legacy general Playwright screenshot writer — serves branch-local page/assets, intercepts @main CDN requests, captures default and language-switched PNG evidence
 *   reads     : pages/{slug}.html (page under test, served from the branch-local repository)
 *               repository assets requested by the rendered page (local server/CDN interception)
 *   writes    : docs/screenshots/{slug}-en.png
 *               docs/screenshots/{slug}-{lang}.png
 *   loaded-by : .github/pull_request_template.md (browser-rendered change evidence instruction)
 *               manual run: node scripts/screenshot-page.js [slug] [lang]
 *   tested-by : review-time browser execution and visual inspection
 *
 *   CHANGE MAP — if you touch X here, also check:
 *     legacy screenshot filename grammar changed:
 *       - lib/screenshot-evidence.js (shared parser)
 *       - lib/build-page-health.js (evidence discovery)
 *       - lib/build-terrain-map.js (representative screenshot projection)
 *       - lib/build-analysis-index.js (evidence projection)
 *     language FAB interaction selectors or Spiral nesting changed:
 *       - widgets/vex-fab.js
 *       - widgets/fab-lang.js
 *       - scripts/screenshot-institutional.js (newer interaction/acceptance pattern)
 *       - rerun this writer on a real current shell page before treating it as compatible
 *     local serving or GitHub Pages path-prefix behavior changed:
 *       - scripts/screenshot-institutional.js (newer bounded local-server pattern)
 *       - hub-style pages using /Vextreme-prefixed asset paths
 * LATTICE:END
 */

'use strict';

const http   = require('http');
const fs     = require('fs');
const path   = require('path');
const { execFileSync } = require('child_process');

// Resolve Playwright from its global install location
const PLAYWRIGHT_PATH = '/opt/node22/lib/node_modules/playwright';
const { chromium } = require(PLAYWRIGHT_PATH);

const ROOT       = path.join(__dirname, '..');
const OUT_DIR    = path.join(ROOT, 'docs', 'screenshots');
const CDN_PREFIX = 'https://cdn.jsdelivr.net/gh/vgong24/vextreme@main';
const VIEWPORT   = { width: 1280, height: 900 };

function parseArgs(argv) {
  const positional = [];
  let assetsRoot = process.env.VEXTREME_ASSETS_ROOT || null;
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--assets-root') {
      assetsRoot = argv[++i];
      if (!assetsRoot) throw new Error('--assets-root requires a path');
    } else if (argv[i].startsWith('--')) {
      throw new Error('unknown argument: ' + argv[i]);
    } else {
      positional.push(argv[i]);
    }
  }
  if (positional.length > 2) throw new Error('usage: node scripts/screenshot-page.js [slug] [lang] [--assets-root <path>]');
  return {
    slug: positional[0] || 'claude-answers-the-doubt',
    lang: positional[1] || 'ja',
    assetsRoot: assetsRoot ? path.resolve(assetsRoot) : null,
  };
}

const options = parseArgs(process.argv.slice(2));
const slug = options.slug;
const lang = options.lang;

// ── MIME types ───────────────────────────────────────────────────────────────

const MIME = {
  '.html':  'text/html; charset=utf-8',
  '.js':    'text/javascript; charset=utf-8',
  '.json':  'application/json; charset=utf-8',
  '.css':   'text/css; charset=utf-8',
  '.png':   'image/png',
  '.jpg':   'image/jpeg',
  '.jpeg':  'image/jpeg',
  '.webp':  'image/webp',
  '.svg':   'image/svg+xml',
  '.woff':  'font/woff',
  '.woff2': 'font/woff2',
  '.ttf':   'font/ttf',
};

function mimeFor(filePath) {
  return MIME[path.extname(filePath)] || 'text/plain';
}

// ── Local HTTP server ─────────────────────────────────────────────────────────
// Serves the whole repo root so the page and all local assets are reachable.

function startServer() {
  return new Promise((resolve) => {
    const server = http.createServer((req, res) => {
      const urlPath = req.url.split('?')[0];
      const filePath = path.join(ROOT, urlPath === '/' ? '/pages/' + slug + '.html' : urlPath);

      fs.readFile(filePath, (err, data) => {
        if (err) {
          res.writeHead(404);
          res.end('Not found: ' + filePath);
          return;
        }
        res.writeHead(200, { 'Content-Type': mimeFor(filePath) });
        res.end(data);
      });
    });

    server.listen(0, '127.0.0.1', () => {
      const { port } = server.address();
      resolve({ server, port });
    });
  });
}

// ── CDN interception ──────────────────────────────────────────────────────────
// Maps CDN URLs to local file paths so we test branch code, not @main.

function localPathFor(cdnUrl) {
  const relative = cdnUrl.replace(CDN_PREFIX, '');
  const clean    = relative.split('?')[0];
  return path.join(ROOT, clean);
}

// ── Screenshot helper ─────────────────────────────────────────────────────────

async function screenshotPage(page, outPath, label) {
  // Wait for arc nav and lang-fab to settle
  await page.waitForTimeout(1200);
  await page.screenshot({ path: outPath, fullPage: true });
  console.log(`  [screenshot] ${label} → ${path.relative(ROOT, outPath)}`);
}

function sourceCommit() {
  const commit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: ROOT, encoding: 'utf8' }).trim();
  if (!/^[0-9a-f]{40}$/i.test(commit)) throw new Error('could not resolve an exact Vextreme source commit');
  return commit.toLowerCase();
}

function publishScreenshotEvidence(outPath, locale) {
  if (!options.assetsRoot) return;
  const ingest = path.join(options.assetsRoot, 'scripts', 'ingest-screenshot-evidence.mjs');
  if (!fs.existsSync(ingest)) {
    throw new Error('Vextreme-Assets screenshot ingest contract not found: ' + ingest);
  }
  const commit = sourceCommit();
  execFileSync(process.execPath, [
    ingest,
    '--file', outPath,
    '--namespace', 'vextreme',
    '--slug', slug,
    '--locale', locale,
    '--theme', 'default',
    '--viewport', String(VIEWPORT.width),
    '--source-repo', 'vgong24/Vextreme',
    '--source-commit', commit,
    '--source-path', 'pages/' + slug + '.html',
    '--capture-kind', 'localization',
  ], { cwd: options.assetsRoot, stdio: 'inherit' });
  console.log(`  [assets] ${locale.toUpperCase()} → structured screenshot evidence (${commit.slice(0, 12)})`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const { server, port } = await startServer();
  const baseUrl = `http://127.0.0.1:${port}`;

  const browser = await chromium.launch({
    executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',
    args: ['--no-sandbox'],
  });

  const context = await browser.newContext({
    viewport: VIEWPORT,
  });

  const page = await context.newPage();

  // Intercept CDN requests → serve local files
  await page.route(`${CDN_PREFIX}/**`, async (route) => {
    const local = localPathFor(route.request().url());
    if (fs.existsSync(local)) {
      const body        = fs.readFileSync(local);
      const contentType = mimeFor(local);
      await route.fulfill({ status: 200, contentType, body });
    } else {
      console.warn(`  [cdn-miss] ${route.request().url()}`);
      await route.continue();
    }
  });

  const pageUrl = `${baseUrl}/pages/${slug}.html`;
  console.log(`\nLoading: ${pageUrl}`);
  await page.goto(pageUrl, { waitUntil: 'networkidle' });

  // ── EN screenshot ────────────────────────────────────────────────────────

  const enOut = path.join(OUT_DIR, `${slug}-en.png`);
  await screenshotPage(page, enOut, 'EN (default)');
  publishScreenshotEvidence(enOut, 'en');

  // ── Switch language via FAB ──────────────────────────────────────────────

  const fabBtn = page.locator('#vex-lang-fab-btn');
  const fabExists = await fabBtn.count();

  if (!fabExists) {
    throw new Error('FAB button not found — refusing to label a localization screenshot without a verified language switch');
  }

  await fabBtn.click();
  await page.waitForTimeout(400); // wheel open animation

  const langItem = page.locator(`.vex-lang-item[data-lang="${lang}"]`);
  const langExists = await langItem.count();
  if (!langExists) {
    throw new Error(`No FAB item found for lang="${lang}" — refusing to capture mislabeled evidence`);
  }

  await langItem.click();
  await page.waitForFunction((expected) => {
    try { return localStorage.getItem('vex-lang') === expected; } catch (error) { return false; }
  }, lang);
  await page.waitForTimeout(250); // allow post-swap layout/fonts to settle

  // Scroll back to top for consistent framing
  await page.evaluate(() => window.scrollTo(0, 0));

  const langOut = path.join(OUT_DIR, `${slug}-${lang}.png`);
  await screenshotPage(page, langOut, `${lang.toUpperCase()} (after verified FAB switch)`);
  publishScreenshotEvidence(langOut, lang);

  await browser.close();
  server.close();

  console.log('\nDone.');
  console.log(`  EN  : docs/screenshots/${slug}-en.png`);
  console.log(`  ${lang.toUpperCase()}  : docs/screenshots/${slug}-${lang}.png`);
  if (options.assetsRoot) console.log(`  Assets evidence checkout: ${options.assetsRoot}`);
})();

// [VXG RealForever]
